openapi: '3.0.0'
info:
  title: Address
  version: '1.0'
  description: ''
servers:
  - url: 'https://api-b2b.bigcommerce.com/api/v2'
paths:
  '/companies/{companyId}/addresses':
    parameters:
      - schema:
          type: string
        name: companyId
        in: path
        required: true
    get:
      summary: Get Company Address List
      tags:
        - address
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                description: ''
                type: object
                x-examples:
                  example-1:
                    code: 200
                    message: SUCCESS
                    data:
                      addresses:
                        '1414':
                          addressId: 1414
                          firstName: Ada
                          lastName: Bob
                          isShipping: 1
                          isBilling: 1
                          addressLine1: line1
                          addressLine2: line1
                          city: AS
                          country:
                            countryName: Argentina
                            countryCode: AR
                          zipCode: '10013'
                          state:
                            stateName: Mendoza
                            stateCode: M
                          phoneNumber: '16732680944'
                          label: label
                      defaultShippingId: '1414'
                      defaultBillingId: '1414'
                      canEnterNewAddress: false
                properties:
                  code:
                    type: number
                  message:
                    type: string
                    minLength: 1
                  data:
                    type: object
                    required:
                      - addresses
                      - defaultShippingId
                      - defaultBillingId
                      - canEnterNewAddress
                    properties:
                      addresses:
                        type: object
                        required:
                          - '1414'
                        properties:
                          '1414':
                            type: object
                            required:
                              - addressId
                              - firstName
                              - lastName
                              - isShipping
                              - isBilling
                              - addressLine1
                              - addressLine2
                              - city
                              - country
                              - zipCode
                              - state
                              - phoneNumber
                              - label
                            properties:
                              addressId:
                                type: number
                              firstName:
                                type: string
                                minLength: 1
                              lastName:
                                type: string
                                minLength: 1
                              isShipping:
                                type: number
                              isBilling:
                                type: number
                              addressLine1:
                                type: string
                                minLength: 1
                              addressLine2:
                                type: string
                                minLength: 1
                              city:
                                type: string
                                minLength: 1
                              country:
                                type: object
                                required:
                                  - countryName
                                  - countryCode
                                properties:
                                  countryName:
                                    type: string
                                    minLength: 1
                                  countryCode:
                                    type: string
                                    minLength: 1
                              zipCode:
                                type: string
                                minLength: 1
                              state:
                                type: object
                                required:
                                  - stateName
                                  - stateCode
                                properties:
                                  stateName:
                                    type: string
                                    minLength: 1
                                  stateCode:
                                    type: string
                                    minLength: 1
                              phoneNumber:
                                type: string
                                minLength: 1
                              label:
                                type: string
                                minLength: 1
                              externalId:
                                type: string
                      defaultShippingId:
                        type: string
                        minLength: 1
                      defaultBillingId:
                        type: string
                        minLength: 1
                      canEnterNewAddress:
                        type: boolean
                required:
                  - code
                  - message
                  - data
              examples:
                example-1:
                  value:
                    code: 200
                    message: SUCCESS
                    data:
                      addresses:
                        '1414':
                          addressId: 1414
                          firstName: Ada
                          lastName: Bob
                          isShipping: 1
                          isBilling: 1
                          addressLine1: line1
                          addressLine2: line1
                          city: AS
                          country:
                            countryName: Argentina
                            countryCode: AR
                          zipCode: '10013'
                          state:
                            stateName: Mendoza
                            stateCode: M
                          phoneNumber: '16732680944'
                          label: label
                          externalId: '2'
                      defaultShippingId: '1414'
                      defaultBillingId: '1414'
                      canEnterNewAddress: false
      operationId: get-companies-companyId-addresses
      description: Get Address List
      x-internal: true
    post:
      summary: Create An Address
      operationId: post-companies-companyId-addresses
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                description: ''
                type: object
                properties:
                  code:
                    type: number
                  message:
                    type: string
                    minLength: 1
                  data:
                    type: object
                    properties:
                      addressId:
                        type: string
                        minLength: 1
                    required:
                      - addressId
                required:
                  - code
                  - message
                  - data
                x-examples:
                  example-1:
                    code: 200
                    message: Success
                    data:
                      addressId: '1418'
              examples:
                example-1:
                  value:
                    code: 200
                    message: Success
                    data:
                      addressId: '1418'
      requestBody:
        content:
          application/json:
            schema:
              description: ''
              type: object
              x-examples:
                example-1:
                  label: address label
                  firstName: Jo
                  lastName: Sweert
                  addressLine1: address line 1
                  addressLine2: address line 2
                  city: Denver
                  zipCode: '80022'
                  phoneNumber: '111111111'
                  country:
                    countryName: Aruba
                    countryCode: AW
                  state:
                    stateName: AS
                    stateCode: ''
                  isShipping: '1'
                  isBilling: '1'
                  isDefaultShipping: '1'
                  isDefaultBilling: '1'
              properties:
                label:
                  type: string
                  minLength: 1
                firstName:
                  type: string
                  minLength: 1
                lastName:
                  type: string
                  minLength: 1
                addressLine1:
                  type: string
                  minLength: 1
                addressLine2:
                  type: string
                  minLength: 1
                city:
                  type: string
                  minLength: 1
                zipCode:
                  type: string
                  minLength: 1
                phoneNumber:
                  type: string
                  minLength: 1
                country:
                  type: object
                  required:
                    - countryName
                    - countryCode
                  properties:
                    countryName:
                      type: string
                      minLength: 1
                    countryCode:
                      type: string
                      minLength: 1
                state:
                  type: object
                  required:
                    - stateName
                    - stateCode
                  properties:
                    stateName:
                      type: string
                      minLength: 1
                    stateCode:
                      type: string
                isShipping:
                  type: string
                  minLength: 1
                  description: '"0":Not set as shipping address, "1":Set as shipping address'
                isBilling:
                  type: string
                  minLength: 1
                  description: '"0":Not set as billing address, "1":Set as billing address'
                isDefaultShipping:
                  type: string
                  minLength: 1
                  description: '"0":Not set as default shipping address, "1":Set as default shipping address'
                isDefaultBilling:
                  type: string
                  minLength: 1
                  description: '"0":Not set as default billing address, "1":Set as default billing address'
                externalId:
                  type: string
              required:
                - label
                - firstName
                - lastName
                - addressLine1
                - addressLine2
                - city
                - zipCode
                - phoneNumber
                - country
                - state
                - isShipping
                - isBilling
                - isDefaultShipping
                - isDefaultBilling
      description: Create An Address
      tags:
        - address
      x-internal: true
  '/companies/{companyId}/addresses/{addressId}':
    parameters:
      - schema:
          type: string
        name: companyId
        in: path
        required: true
      - schema:
          type: string
        name: addressId
        in: path
        required: true
    get:
      summary: Get An Address
      tags:
        - address
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                description: ''
                type: object
                x-examples:
                  example-1:
                    code: 200
                    message: Success
                    data:
                      addressId: '1418'
                      firstName: Jo
                      lastName: Sweert
                      addressLine1: address line 1
                      addressLine2: address line 2
                      country:
                        countryName: Aruba
                        countryCode: AW
                      state:
                        stateName: AS
                        stateCode: ''
                      city: Denver
                      phoneNumber: '111111111'
                      zipCode: '80022'
                      isShipping: '1'
                      isBilling: '1'
                      isDefaultShipping: '1'
                      isDefaultBilling: '1'
                      label: address label
                properties:
                  code:
                    type: number
                  message:
                    type: string
                    minLength: 1
                  data:
                    type: object
                    required:
                      - addressId
                      - firstName
                      - lastName
                      - addressLine1
                      - addressLine2
                      - country
                      - state
                      - city
                      - phoneNumber
                      - zipCode
                      - isShipping
                      - isBilling
                      - isDefaultShipping
                      - isDefaultBilling
                      - label
                    properties:
                      addressId:
                        type: string
                        minLength: 1
                      firstName:
                        type: string
                        minLength: 1
                      lastName:
                        type: string
                        minLength: 1
                      addressLine1:
                        type: string
                        minLength: 1
                      addressLine2:
                        type: string
                        minLength: 1
                      country:
                        type: object
                        required:
                          - countryName
                          - countryCode
                        properties:
                          countryName:
                            type: string
                            minLength: 1
                          countryCode:
                            type: string
                            minLength: 1
                      state:
                        type: object
                        required:
                          - stateName
                          - stateCode
                        properties:
                          stateName:
                            type: string
                            minLength: 1
                          stateCode:
                            type: string
                      city:
                        type: string
                        minLength: 1
                      phoneNumber:
                        type: string
                        minLength: 1
                      zipCode:
                        type: string
                        minLength: 1
                      isShipping:
                        type: string
                        minLength: 1
                      isBilling:
                        type: string
                        minLength: 1
                      isDefaultShipping:
                        type: string
                        minLength: 1
                      isDefaultBilling:
                        type: string
                        minLength: 1
                      label:
                        type: string
                        minLength: 1
                      externalId:
                        type: string
                required:
                  - code
                  - message
                  - data
              examples:
                example-1:
                  value:
                    code: 200
                    message: Success
                    data:
                      addressId: '1418'
                      firstName: Jo
                      lastName: Sweert
                      addressLine1: address line 1
                      addressLine2: address line 2
                      country:
                        countryName: Aruba
                        countryCode: AW
                      state:
                        stateName: AS
                        stateCode: ''
                      city: Denver
                      phoneNumber: '111111111'
                      zipCode: '80022'
                      isShipping: '1'
                      isBilling: '1'
                      isDefaultShipping: '1'
                      isDefaultBilling: '1'
                      label: address label
                      externalId: '4'
      operationId: get-companies-companyId-addresses-addressId
      description: Get An Address
      x-internal: true
    put:
      summary: Update An Address
      operationId: put-companies-companyId-addresses-addressId
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                description: ''
                type: object
                properties:
                  code:
                    type: number
                  message:
                    type: string
                    minLength: 1
                  data:
                    type: object
                    properties:
                      addressId:
                        type: string
                        minLength: 1
                    required:
                      - addressId
                required:
                  - code
                  - message
                  - data
                x-examples:
                  example-1:
                    code: 200
                    message: Success
                    data:
                      addressId: '1418'
              examples:
                example-1:
                  value:
                    code: 200
                    message: Success
                    data:
                      addressId: '1418'
      description: Update An Address
      requestBody:
        content:
          application/json:
            schema:
              description: ''
              type: object
              x-examples:
                example-1:
                  label: address label
                  firstName: Jo
                  lastName: Sweert
                  addressLine1: address line 1
                  addressLine2: address line 2
                  city: Denver
                  zipCode: '80022'
                  phoneNumber: '111111112'
                  country:
                    countryName: Aruba
                    countryCode: AW
                  state:
                    stateName: AS
                    stateCode: ''
                  isShipping: '1'
                  isBilling: '1'
                  isDefaultShipping: '1'
                  isDefaultBilling: '1'
                  addressId: '1418'
              properties:
                label:
                  type: string
                  minLength: 1
                firstName:
                  type: string
                  minLength: 1
                lastName:
                  type: string
                  minLength: 1
                addressLine1:
                  type: string
                  minLength: 1
                addressLine2:
                  type: string
                  minLength: 1
                city:
                  type: string
                  minLength: 1
                zipCode:
                  type: string
                  minLength: 1
                phoneNumber:
                  type: string
                  minLength: 1
                country:
                  type: object
                  required:
                    - countryName
                    - countryCode
                  properties:
                    countryName:
                      type: string
                      minLength: 1
                    countryCode:
                      type: string
                      minLength: 1
                state:
                  type: object
                  required:
                    - stateName
                    - stateCode
                  properties:
                    stateName:
                      type: string
                      minLength: 1
                    stateCode:
                      type: string
                isShipping:
                  type: string
                  minLength: 1
                isBilling:
                  type: string
                  minLength: 1
                isDefaultShipping:
                  type: string
                  minLength: 1
                isDefaultBilling:
                  type: string
                  minLength: 1
                addressId:
                  type: string
                  minLength: 1
                externalId:
                  type: string
              required:
                - label
                - firstName
                - lastName
                - addressLine1
                - addressLine2
                - city
                - zipCode
                - phoneNumber
                - country
                - state
                - isShipping
                - isBilling
                - isDefaultShipping
                - isDefaultBilling
                - addressId
      tags:
        - address
      x-internal: true
  '/companies/{companyId}/addresses/{addressId}/activation':
    parameters:
      - schema:
          type: string
        name: companyId
        in: path
        required: true
      - schema:
          type: string
        name: addressId
        in: path
        required: true
    put:
      summary: Mark An Address As Active Or Inactive
      operationId: put-companies-companyId-addresses-addressId-activation
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                description: ''
                type: object
                properties:
                  code:
                    type: number
                  message:
                    type: string
                    minLength: 1
                  data:
                    type: object
                    properties:
                      addressId:
                        type: string
                        minLength: 1
                    required:
                      - addressId
                required:
                  - code
                  - message
                  - data
                x-examples:
                  example-1:
                    code: 200
                    message: Success
                    data:
                      addressId: '1418'
              examples:
                example-1:
                  value:
                    code: 200
                    message: Success
                    data:
                      addressId: '1418'
      description: Mark An Address As Active Or Inactive
      tags:
        - address
      x-internal: true
  '/companies/{companyId}/default-addresses':
    parameters:
      - schema:
          type: string
        name: companyId
        in: path
        required: true
    get:
      summary: Get Default Addresses By CompanyId
      tags:
        - address
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                description: ''
                type: object
                x-examples:
                  example-1:
                    code: 200
                    message: Success
                    data:
                      shipping:
                        addressId: '1414'
                        firstName: Ada
                        lastName: Bob
                        addressLine1: line1
                        addressLine2: line1
                        country:
                          countryName: Argentina
                          countryCode: AR
                        state:
                          stateName: Mendoza
                          stateCode: M
                        city: AS
                        phoneNumber: '16732680944'
                        zipCode: '10013'
                        label: label
                      billing:
                        addressId: '1414'
                        firstName: Ada
                        lastName: Bob
                        addressLine1: line1
                        addressLine2: line1
                        country:
                          countryName: Argentina
                          countryCode: AR
                        state:
                          stateName: Mendoza
                          stateCode: M
                        city: AS
                        phoneNumber: '16732680944'
                        zipCode: '10013'
                        label: label
                properties:
                  code:
                    type: number
                  message:
                    type: string
                    minLength: 1
                  data:
                    type: object
                    required:
                      - shipping
                      - billing
                    properties:
                      shipping:
                        type: object
                        required:
                          - addressId
                          - firstName
                          - lastName
                          - addressLine1
                          - addressLine2
                          - country
                          - state
                          - city
                          - phoneNumber
                          - zipCode
                          - label
                        properties:
                          addressId:
                            type: string
                            minLength: 1
                          firstName:
                            type: string
                            minLength: 1
                          lastName:
                            type: string
                            minLength: 1
                          addressLine1:
                            type: string
                            minLength: 1
                          addressLine2:
                            type: string
                            minLength: 1
                          country:
                            type: object
                            required:
                              - countryName
                              - countryCode
                            properties:
                              countryName:
                                type: string
                                minLength: 1
                              countryCode:
                                type: string
                                minLength: 1
                          state:
                            type: object
                            required:
                              - stateName
                              - stateCode
                            properties:
                              stateName:
                                type: string
                                minLength: 1
                              stateCode:
                                type: string
                                minLength: 1
                          city:
                            type: string
                            minLength: 1
                          phoneNumber:
                            type: string
                            minLength: 1
                          zipCode:
                            type: string
                            minLength: 1
                          label:
                            type: string
                            minLength: 1
                          externalId:
                            type: string
                      billing:
                        type: object
                        required:
                          - addressId
                          - firstName
                          - lastName
                          - addressLine1
                          - addressLine2
                          - country
                          - state
                          - city
                          - phoneNumber
                          - zipCode
                          - label
                        properties:
                          addressId:
                            type: string
                            minLength: 1
                          firstName:
                            type: string
                            minLength: 1
                          lastName:
                            type: string
                            minLength: 1
                          addressLine1:
                            type: string
                            minLength: 1
                          addressLine2:
                            type: string
                            minLength: 1
                          country:
                            type: object
                            required:
                              - countryName
                              - countryCode
                            properties:
                              countryName:
                                type: string
                                minLength: 1
                              countryCode:
                                type: string
                                minLength: 1
                          state:
                            type: object
                            required:
                              - stateName
                              - stateCode
                            properties:
                              stateName:
                                type: string
                                minLength: 1
                              stateCode:
                                type: string
                                minLength: 1
                          city:
                            type: string
                            minLength: 1
                          phoneNumber:
                            type: string
                            minLength: 1
                          zipCode:
                            type: string
                            minLength: 1
                          label:
                            type: string
                            minLength: 1
                          '':
                            type: string
                required:
                  - code
                  - message
                  - data
              examples:
                example-1:
                  value:
                    code: 200
                    message: Success
                    data:
                      shipping:
                        addressId: '1414'
                        firstName: Ada
                        lastName: Bob
                        addressLine1: line1
                        addressLine2: line1
                        country:
                          countryName: Argentina
                          countryCode: AR
                        state:
                          stateName: Mendoza
                          stateCode: M
                        city: AS
                        phoneNumber: '16732680944'
                        zipCode: '10013'
                        label: label
                        externalId: '1'
                      billing:
                        addressId: '1414'
                        firstName: Ada
                        lastName: Bob
                        addressLine1: line1
                        addressLine2: line1
                        country:
                          countryName: Argentina
                          countryCode: AR
                        state:
                          stateName: Mendoza
                          stateCode: M
                        city: AS
                        phoneNumber: '16732680944'
                        zipCode: '10013'
                        label: label
                        externalId: '1'
      operationId: get-companies-companyId-default-addresses
      description: Get Default Addresses By CompanyId
      x-internal: true
  '/companies/{companyId}/addresses/searches':
    parameters:
      - schema:
          type: string
        name: companyId
        in: path
        required: true
    get:
      summary: Search Address
      tags:
        - address
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                description: ''
                type: object
                x-examples:
                  example-1:
                    code: 200
                    message: SUCCESS
                    data:
                      addressBookStatus: '1'
                      defaultAddress:
                        companyId: '5716'
                        companyName: levi-test
                        companyAddress: address line 1 address line 2
                        companyCountry: Aruba
                        companyCountryCode: ''
                        companyState: ''
                        companyStateCode: ''
                        companyCity: Denver
                        companyZipCode: '80022'
                        firstName: ''
                        lastName: ''
                        phoneNumber: '17195453626'
                        label: ''
                      list:
                        - companyId: '5716'
                          companyName: levi-test
                          companyAddress: line1 line1
                          companyCountry: Argentina
                          companyCountryCode: AR
                          companyState: Mendoza
                          companyStateCode: M
                          companyCity: AS
                          companyZipCode: '10013'
                          firstName: Ada
                          lastName: Bob
                          phoneNumber: '16732680944'
                          label: label
                      pagination:
                        totalCount: 1
                        offset: 0
                        limit: 10
                properties:
                  code:
                    type: number
                  message:
                    type: string
                    minLength: 1
                  data:
                    type: object
                    required:
                      - addressBookStatus
                      - defaultAddress
                      - list
                      - pagination
                    properties:
                      addressBookStatus:
                        type: string
                        minLength: 1
                      defaultAddress:
                        type: object
                        required:
                          - companyId
                          - companyName
                          - companyAddress
                          - companyCountry
                          - companyCountryCode
                          - companyState
                          - companyStateCode
                          - companyCity
                          - companyZipCode
                          - firstName
                          - lastName
                          - phoneNumber
                          - label
                        properties:
                          companyId:
                            type: string
                            minLength: 1
                          companyName:
                            type: string
                            minLength: 1
                          companyAddress:
                            type: string
                            minLength: 1
                          companyCountry:
                            type: string
                            minLength: 1
                          companyCountryCode:
                            type: string
                          companyState:
                            type: string
                          companyStateCode:
                            type: string
                          companyCity:
                            type: string
                            minLength: 1
                          companyZipCode:
                            type: string
                            minLength: 1
                          firstName:
                            type: string
                          lastName:
                            type: string
                          phoneNumber:
                            type: string
                            minLength: 1
                          label:
                            type: string
                      list:
                        type: array
                        uniqueItems: true
                        minItems: 1
                        items:
                          type: object
                          properties:
                            companyId:
                              type: string
                              minLength: 1
                            companyName:
                              type: string
                              minLength: 1
                            companyAddress:
                              type: string
                              minLength: 1
                            companyCountry:
                              type: string
                              minLength: 1
                            companyCountryCode:
                              type: string
                              minLength: 1
                            companyState:
                              type: string
                              minLength: 1
                            companyStateCode:
                              type: string
                              minLength: 1
                            companyCity:
                              type: string
                              minLength: 1
                            companyZipCode:
                              type: string
                              minLength: 1
                            firstName:
                              type: string
                              minLength: 1
                            lastName:
                              type: string
                              minLength: 1
                            phoneNumber:
                              type: string
                              minLength: 1
                            label:
                              type: string
                              minLength: 1
                            '':
                              type: string
                          required:
                            - companyId
                            - companyName
                            - companyAddress
                            - companyCountry
                            - companyCountryCode
                            - companyState
                            - companyStateCode
                            - companyCity
                            - companyZipCode
                            - firstName
                            - lastName
                            - phoneNumber
                            - label
                      pagination:
                        type: object
                        required:
                          - totalCount
                          - offset
                          - limit
                        properties:
                          totalCount:
                            type: number
                          offset:
                            type: number
                          limit:
                            type: number
                required:
                  - code
                  - message
                  - data
              examples:
                example-1:
                  value:
                    code: 200
                    message: SUCCESS
                    data:
                      addressBookStatus: '1'
                      defaultAddress:
                        companyId: '5716'
                        companyName: company name
                        companyAddress: address line 1 address line 2
                        companyCountry: Aruba
                        companyCountryCode: ''
                        companyState: ''
                        companyStateCode: ''
                        companyCity: Denver
                        companyZipCode: '80022'
                        firstName: ''
                        lastName: ''
                        phoneNumber: '17195453626'
                        label: ''
                      list:
                        - companyId: '5716'
                          companyName: company name
                          companyAddress: line1 line1
                          companyCountry: Argentina
                          companyCountryCode: AR
                          companyState: Mendoza
                          companyStateCode: M
                          companyCity: AS
                          companyZipCode: '10013'
                          firstName: Ada
                          lastName: Bob
                          phoneNumber: '16732680944'
                          label: label
                      pagination:
                        totalCount: 1
                        offset: 0
                        limit: 10
      operationId: get-companies-companyId-addresses-searches
      parameters:
        - schema:
            type: string
          in: query
          name: offset
          description: Pagination offset
        - schema:
            type: string
          in: query
          name: limit
          description: Pagination limit
        - schema:
            type: string
          in: query
          name: q
          description: Query string
      description: Search Address
      x-internal: true
    post:
      summary: Search For Address With Multiple Search Filter
      operationId: post-companies-companyId-addresses-searches
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                description: ''
                type: object
                x-examples:
                  example-1:
                    code: 200
                    message: Success
                    data:
                      pagination:
                        totalCount: 1
                        offset: 0
                        limit: 10
                      list:
                        - addressId: '1414'
                          firstName: Ada
                          lastName: Bob
                          addressLine1: line1
                          addressLine2: line1
                          city: AS
                          state:
                            stateName: Mendoza
                            stateCode: M
                          country:
                            countryName: Argentina
                            countryCode: AR
                          phoneNumber: '16732680944'
                          zipCode: '10013'
                          isShipping: '1'
                          isBilling: '1'
                          isDefaultShipping: '1'
                          isDefaultBilling: '1'
                          label: label
                      defaultAddressIds:
                        shippingAddressId: '1414'
                        billingAddressId: '1414'
                properties:
                  code:
                    type: number
                  message:
                    type: string
                    minLength: 1
                  data:
                    type: object
                    required:
                      - pagination
                      - list
                      - defaultAddressIds
                    properties:
                      pagination:
                        type: object
                        required:
                          - totalCount
                          - offset
                          - limit
                        properties:
                          totalCount:
                            type: number
                          offset:
                            type: number
                          limit:
                            type: number
                      list:
                        type: array
                        uniqueItems: true
                        minItems: 1
                        items:
                          type: object
                          properties:
                            addressId:
                              type: string
                              minLength: 1
                            firstName:
                              type: string
                              minLength: 1
                            lastName:
                              type: string
                              minLength: 1
                            addressLine1:
                              type: string
                              minLength: 1
                            addressLine2:
                              type: string
                              minLength: 1
                            city:
                              type: string
                              minLength: 1
                            state:
                              type: object
                              properties:
                                stateName:
                                  type: string
                                  minLength: 1
                                stateCode:
                                  type: string
                                  minLength: 1
                              required:
                                - stateName
                                - stateCode
                            country:
                              type: object
                              properties:
                                countryName:
                                  type: string
                                  minLength: 1
                                countryCode:
                                  type: string
                                  minLength: 1
                              required:
                                - countryName
                                - countryCode
                            phoneNumber:
                              type: string
                              minLength: 1
                            zipCode:
                              type: string
                              minLength: 1
                            isShipping:
                              type: string
                              minLength: 1
                            isBilling:
                              type: string
                              minLength: 1
                            isDefaultShipping:
                              type: string
                              minLength: 1
                            isDefaultBilling:
                              type: string
                              minLength: 1
                            label:
                              type: string
                              minLength: 1
                            '':
                              type: string
                          required:
                            - addressId
                            - firstName
                            - lastName
                            - addressLine1
                            - addressLine2
                            - city
                            - phoneNumber
                            - zipCode
                            - isShipping
                            - isBilling
                            - isDefaultShipping
                            - isDefaultBilling
                            - label
                      defaultAddressIds:
                        type: object
                        required:
                          - shippingAddressId
                          - billingAddressId
                        properties:
                          shippingAddressId:
                            type: string
                            minLength: 1
                          billingAddressId:
                            type: string
                            minLength: 1
                required:
                  - code
                  - message
                  - data
              examples:
                example-1:
                  value:
                    code: 200
                    message: Success
                    data:
                      pagination:
                        totalCount: 1
                        offset: 0
                        limit: 10
                      list:
                        - addressId: '1414'
                          firstName: Ada
                          lastName: Bob
                          addressLine1: line1
                          addressLine2: line1
                          city: AS
                          state:
                            stateName: Mendoza
                            stateCode: M
                          country:
                            countryName: Argentina
                            countryCode: AR
                          phoneNumber: '16732680944'
                          zipCode: '10013'
                          isShipping: '1'
                          isBilling: '1'
                          isDefaultShipping: '1'
                          isDefaultBilling: '1'
                          label: label
                          externalId: '100'
                      defaultAddressIds:
                        shippingAddressId: '1414'
                        billingAddressId: '1414'
      description: Search For Address With Multiple Search Filter
      requestBody:
        content:
          application/json:
            schema:
              description: ''
              type: object
              properties:
                offset:
                  type: number
                limit:
                  type: number
                q:
                  type: string
                filters:
                  type: object
                  properties:
                    firstName:
                      type: string
                    lastName:
                      type: string
                    address:
                      type: string
                    city:
                      type: string
                    country:
                      type: string
                    state:
                      type: string
                    phoneNumber:
                      type: string
                    zipCode:
                      type: string
                    label:
                      type: string
                    addressType:
                      type: object
                      properties:
                        isShipping:
                          type: string
                          minLength: 1
                        isBilling:
                          type: string
                          minLength: 1
                      required:
                        - isShipping
                        - isBilling
                  required:
                    - firstName
                    - lastName
                    - address
                    - city
                    - country
                    - state
                    - phoneNumber
                    - zipCode
                    - label
                    - addressType
              required:
                - offset
                - limit
                - q
                - filters
              x-examples:
                example-1:
                  offset: 0
                  limit: 10
                  q: ''
                  filters:
                    firstName: ''
                    lastName: ''
                    address: ''
                    city: ''
                    country: ''
                    state: ''
                    phoneNumber: ''
                    zipCode: ''
                    label: ''
                    addressType:
                      isShipping: '1'
                      isBilling: '1'
      tags:
        - address
      x-internal: true
  /companies/addresses/bulk-creation/upload:
    post:
      summary: Upload Address File
      tags:
        - address
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                description: ''
                type: object
                x-examples:
                  example-1:
                    code: 200
                    message: SUCCESS
                    data:
                      isReady: '0'
                properties:
                  code:
                    type: number
                  message:
                    type: string
                    minLength: 1
                  data:
                    type: object
                    required:
                      - isReady
                    properties:
                      isReady:
                        type: string
                        minLength: 1
                        description: '"0":doing, "1":finished'
                required:
                  - code
                  - message
                  - data
              examples:
                example-1:
                  value:
                    code: 200
                    message: SUCCESS
                    data:
                      isReady: '0'
      operationId: get-companies-addresses-bulk-creation-upload
      description: Upload Address File
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                addressFile:
                  type:
                    - object
                    - string
      x-internal: true
components:
  schemas: {}
  securitySchemes:
    authToken:
      name: authToken
      type: apiKey
      in: header
security:
  - authToken: []
tags:
  - name: address
x-internal: true
