openapi: 3.0.1
info:
  title: Invoices
  description: BigCommerce B2B Edition Invoice
  contact: {}
  version: v2
servers:
  - url: 'https://api-b2b.bigcommerce.com/api/v2/ip/storefront'
security:
  - authToken: []
tags:
  - name: Invoice
    description: Invoice
components:
  securitySchemes:
    authToken:
      name: authToken
      type: apiKey
      in: header
  schemas:
    invoice:
      description: Invoice model
      type: object
      x-examples:
        example-1:
          id: 0
          customerId: string
          externalCustomerId: string
          externalId: string
          invoiceNumber: string
          type: string
          dueDate: 0
          status: 0
          orderNumber: string
          purchaseOrderNumber: string
          details:
            type: string
            header:
              costLines:
                - amount:
                    code: string
                    value: string
                  description: string
              orderDate: 0
              billingAddress:
                city: string
                state: string
                country: string
                street1: string
                street2: string
                zipCode: string
                lastName: string
                firstName: string
                customFields: {}
              customerFields: string
              shippingAddresses:
                - city: string
                  state: string
                  country: string
                  street1: string
                  street2: string
                  zipCode: string
                  lastName: string
                  firstName: string
                  customFields: {}
            details:
              shipments:
                - {}
              lineItems:
                - sku: string
                  type: string
                  comments: string
                  quantity: string
                  unitPrice:
                    code: string
                    value: string
                  description: string
                  customFields: {}
                  unitDiscount:
                    code: string
                    value: string
          isPendingPayment: 0
          source: 0
          originalBalance:
            code: string
            value: string
          openBalance:
            code: string
            value: string
          customerName: string
      title: ''
      x-internal: false
      properties:
        id:
          type: number
          description: Invoice ID
          readOnly: true
        customerId:
          type: string
          minLength: 1
          description: B2B Edition Company ID
        externalCustomerId:
          type: string
          minLength: 1
          description: ID of a company associated with a third party
        externalId:
          type: string
          minLength: 1
          description: The ID of the invoice associated with the third party
        invoiceNumber:
          type: string
          minLength: 1
          description: Invoice no.
        type:
          type: string
          minLength: 1
          description: Invoice Type
        dueDate:
          type: number
          description: Invoice due date
        status:
          type: number
          description: Invoice status
        orderNumber:
          type: string
          minLength: 1
          description: BigCommerce order ID
        purchaseOrderNumber:
          type: string
          minLength: 1
          description: PO no.
        details:
          type: object
          description: Invoice details
          properties:
            type:
              type: string
              minLength: 1
              description: Invoice details type
            header:
              type: object
              required:
                - costLines
                - billingAddress
                - shippingAddresses
              properties:
                costLines:
                  type: array
                  uniqueItems: true
                  minItems: 1
                  description: Invoice cost information
                  items:
                    type: object
                    properties:
                      amount:
                        type: object
                        description: cost amount
                        required:
                          - code
                          - value
                        properties:
                          code:
                            type: string
                            minLength: 1
                          value:
                            type: string
                            minLength: 1
                      description:
                        type: string
                        minLength: 1
                        description: cost description
                    required:
                      - amount
                      - description
                orderDate:
                  type: number
                  description: Invoice order creation time
                billingAddress:
                  type: object
                  description: Invoice billing address
                  required:
                    - city
                    - state
                    - country
                    - street1
                    - street2
                    - zipCode
                    - lastName
                    - firstName
                  properties:
                    city:
                      type: string
                      minLength: 1
                    state:
                      type: string
                      minLength: 1
                    country:
                      type: string
                      minLength: 1
                    street1:
                      type: string
                      minLength: 1
                    street2:
                      type: string
                      minLength: 1
                    zipCode:
                      type: string
                      minLength: 1
                    lastName:
                      type: string
                      minLength: 1
                    firstName:
                      type: string
                      minLength: 1
                    customFields:
                      type: object
                customerFields:
                  type: string
                  minLength: 1
                  description: User-defined additional fields
                shippingAddresses:
                  type: array
                  uniqueItems: true
                  minItems: 1
                  description: Invoice shipping addresses
                  items:
                    type: object
                    properties:
                      city:
                        type: string
                        minLength: 1
                      state:
                        type: string
                        minLength: 1
                      country:
                        type: string
                        minLength: 1
                      street1:
                        type: string
                        minLength: 1
                      street2:
                        type: string
                        minLength: 1
                      zipCode:
                        type: string
                        minLength: 1
                      lastName:
                        type: string
                        minLength: 1
                      firstName:
                        type: string
                        minLength: 1
                      customFields:
                        type: object
                    required:
                      - city
                      - state
                      - country
                      - street1
                      - street2
                      - zipCode
                      - lastName
                      - firstName
            details:
              type: object
              properties:
                shipments:
                  type: array
                  uniqueItems: true
                  minItems: 1
                  description: Invoice shipments information
                  items:
                    type: object
                    properties:
                      addressIndex:
                        type: string
                        description: address ID
                      shipDate:
                        type: string
                        description: Time of shipment
                      shipVia:
                        type: string
                      trackingNumber:
                        type: string
                        description: tracking number
                      comments:
                        type: string
                        description: comments
                      customFields:
                        type: object
                    required:
                      - addressIndex
                      - shipDate
                      - shipVia
                      - trackingNumber
                      - comments
                lineItems:
                  type: array
                  uniqueItems: true
                  minItems: 1
                  description: Invoice Product Information
                  items:
                    type: object
                    properties:
                      sku:
                        type: string
                        minLength: 1
                        description: Product sku
                      type:
                        type: string
                        minLength: 1
                        description: product type
                      comments:
                        type: string
                        minLength: 1
                      quantity:
                        type: string
                        minLength: 1
                        description: product qyantity
                      unitPrice:
                        type: object
                        description: product unit price
                        required:
                          - code
                          - value
                        properties:
                          code:
                            type: string
                            minLength: 1
                            description: currency code
                            example: USA
                          value:
                            type: string
                            minLength: 1
                            description: amount
                      description:
                        type: string
                        minLength: 1
                        description: product description
                      customFields:
                        type: object
                      unitDiscount:
                        type: object
                        description: product unit discount
                        required:
                          - code
                          - value
                        properties:
                          code:
                            type: string
                            minLength: 1
                            description: currency code
                          value:
                            type: string
                            minLength: 1
                            description: amount
                    required:
                      - sku
                      - type
                      - comments
                      - quantity
                      - unitPrice
                      - description
                      - unitDiscount
              required:
                - lineItems
          required:
            - type
            - header
        isPendingPayment:
          type: number
          readOnly: true
        source:
          type: number
          description: Source of invoice   0 is B2B Edition   1 is External
          enum:
            - 0
            - 1
          example: 0
        originalBalance:
          type: object
          description: Origin balance
          required:
            - code
            - value
          properties:
            code:
              type: string
              minLength: 1
              description: currency code
            value:
              type: string
              minLength: 1
              description: amount
        openBalance:
          type: object
          description: Invoice open balance
          required:
            - code
            - value
          properties:
            code:
              type: string
              minLength: 1
              description: currency code
            value:
              type: string
              minLength: 1
              description: amount
        customerName:
          type: string
          minLength: 1
          description: BigCommerce customer group name
          readOnly: true
        createdAt:
          type: string
          description: Invoice creation time
        updatedAt:
          type: string
          description: Invoice last updated time
          readOnly: true
      required:
        - customerId
        - invoiceNumber
        - type
        - status
        - originalBalance
        - openBalance
paths:
  '/invoices/{invoiceId}':
    parameters:
      - schema:
          type: string
        name: invoiceId
        in: path
        required: true
        description: invoice id
    get:
      summary: Get invoice detail
      operationId: get-invoices-invoiceId
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                description: ''
                type: object
                properties:
                  code:
                    type: number
                  data:
                    $ref: '#/components/schemas/invoice'
                  meta:
                    type: object
                    required:
                      - message
                    properties:
                      message:
                        type: string
                        minLength: 1
                required:
                  - meta
              examples:
                '200':
                  value:
                    code: 200
                    data:
                      id: 9
                      customerId: '95075'
                      externalId: null
                      externalCustomerId: null
                      invoiceNumber: '00000009'
                      type: Invoice on Shipment
                      dueDate: 1617675497
                      status: 1
                      orderNumber: '104'
                      purchaseOrderNumber: null
                      details:
                        type: StandardInvoiceDetails
                        header:
                          costLines:
                            - amount:
                                code: USD
                                value: '349.5000'
                              description: Subtotal
                            - amount:
                                code: USD
                                value: '0.0000'
                              description: Freight
                            - amount:
                                code: USD
                                value: '0.0000'
                              description: Sales Tax
                          orderDate: 1616809386
                          billingAddress:
                            city: 成都
                            state: District of Columbia
                            country: United States
                            street1: tianfuwujie
                            street2: ruanjianyuan
                            zipCode: '123'
                            lastName: xu
                            firstName: stanton
                            customFields: {}
                          customerFields: ''
                          shippingAddresses:
                            - city: 成都
                              state: District of Columbia
                              country: United States
                              street1: tianfuwujie
                              street2: ruanjianyuan
                              zipCode: '123'
                              lastName: xu
                              firstName: stanton
                              customFields: {}
                        details:
                          shipments: []
                          lineItems:
                            - sku: DPB
                              type: physical
                              comments: ''
                              quantity: '10'
                              unitPrice:
                                code: USD
                                value: '34.95'
                              description: '[Sample] Dustpan & Brush'
                              customFields: {}
                              unitDiscount:
                                code: USD
                                value: '12'
                            - sku: DD
                              type: product
                              comments: ''
                              quantity: '10'
                              unitPrice:
                                code: USD
                                value: '3'
                              description: '[Sample] Dustpan '
                              customFields: {}
                              unitDiscount:
                                code: USD
                                value: '1'
                      isPendingPayment: 1
                      source: 0
                      originalBalance:
                        code: USD
                        value: '349.5000'
                      openBalance:
                        code: USD
                        value: '913.4300'
                      customerName: silk
                    meta:
                      message: SUCCESS
                '404':
                  value:
                    code: 404
                    data: []
                    meta:
                      message: Not Found Error
                      errors: Invoice does not exist
                example-3:
                  value:
                    code: 0
                    data:
                      id: 0
                      customerId: string
                      externalCustomerId: string
                      externalId: string
                      invoiceNumber: string
                      type: string
                      dueDate: 0
                      status: 0
                      orderNumber: string
                      purchaseOrderNumber: string
                      details:
                        type: string
                        header:
                          costLines:
                            - amount:
                                code: string
                                value: string
                              description: string
                          orderDate: 0
                          billingAddress:
                            city: string
                            state: string
                            country: string
                            street1: string
                            street2: string
                            zipCode: string
                            lastName: string
                            firstName: string
                            customFields: {}
                          customerFields: string
                          shippingAddresses:
                            - city: string
                              state: string
                              country: string
                              street1: string
                              street2: string
                              zipCode: string
                              lastName: string
                              firstName: string
                              customFields: {}
                        details:
                          shipments:
                            - {}
                          lineItems:
                            - sku: string
                              type: string
                              comments: string
                              quantity: string
                              unitPrice:
                                code: string
                                value: string
                              description: string
                              customFields: {}
                              unitDiscount:
                                code: string
                                value: string
                      isPendingPayment: 0
                      source: 0
                      originalBalance:
                        code: string
                        value: string
                      openBalance:
                        code: string
                        value: string
                      customerName: string
                    meta:
                      message: string
      description: get invoice detail
      parameters:
        - schema:
            type: string
          in: header
          name: authToken
          description: API token
          required: true
      tags:
        - Invoice
      x-internal: true
  /invoices:
    parameters: []
    get:
      summary: Get invoices
      operationId: get-invoices
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                description: ''
                type: object
                properties:
                  code:
                    type: number
                  data:
                    type: array
                    uniqueItems: true
                    minItems: 1
                    items:
                      $ref: '#/components/schemas/invoice'
              examples:
                example:
                  value:
                    code: 200
                    data:
                      - id: 33
                        customerId: '3'
                        externalId: null
                        externalCustomerId: null
                        invoiceNumber: '00000033'
                        type: Invoice on Shipment
                        dueDate: 1619826907
                        status: 0
                        orderNumber: '132'
                        purchaseOrderNumber: null
                        details:
                          type: StandardInvoiceDetails
                          header:
                            costLines:
                              - amount:
                                  code: USD
                                  value: '400.0000'
                                description: Subtotal
                              - amount:
                                  code: USD
                                  value: '0.0000'
                                description: Freight
                              - amount:
                                  code: USD
                                  value: '0.0000'
                                description: Sales Tax
                            orderDate: 1618246864
                            billingAddress:
                              city: montreal
                              state: California
                              country: United States
                              street1: test
                              street2: test
                              zipCode: '111111'
                              lastName: test
                              firstName: test
                              customFields: {}
                            customerFields: ''
                            shippingAddresses:
                              - city: montreal
                                state: California
                                country: United States
                                street1: test
                                street2: test
                                zipCode: '111111'
                                lastName: test
                                firstName: test
                                customFields: {}
                          details:
                            lineItems:
                              - sku: CLC
                                type: physical
                                comments: ''
                                quantity: 2
                                unitPrice:
                                  code: USD
                                  value: '200.0000'
                                description: '[Sample] Canvas Laundry Cart'
                                customFields: {}
                                unitDiscount:
                                  code: USD
                                  value: 0
                            shipments: []
                        isPendingPayment: 1
                        source: 0
                        originalBalance:
                          code: USD
                          value: '400.0000'
                        openBalance:
                          code: USD
                          value: '400.0000'
                        customerName: ABC123
      description: get invoices
      parameters:
        - schema:
            type: string
          in: header
          name: authToken
          description: API Token
          required: true
        - schema:
            type: number
          in: query
          name: offset
        - schema:
            type: number
          in: query
          name: limit
        - schema:
            type: string
            enum:
              - DESC
              - ASC
            example: DESC
          in: query
          name: orderBy
          description: '"DESC" or "ASC"'
        - schema:
            type: string
            enum:
              - invoiceNumber
              - createdAt
              - customerId
              - externalCustomerId
              - dueDate
              - updatedAt
              - isPendingPayment
              - openBalance
              - originalBalance
              - status
            example: invoiceNumber
          in: query
          name: sortBy
          description: Sort by the field value
        - schema:
            type: string
            enum:
              - invoiceNumber
              - type
              - orderNumber
              - purchaseOrderNumber
              - customerId
              - externalCustomerId
            example: invoiceNumber
          in: query
          name: searchBy
          description: Filter by a field
        - schema:
            type: string
          in: query
          name: q
          description: 'Keyword queries are performed on fields corresponding to the value of "searchBy" or, if "searchBy" is empty, on all fields supported by "searchBy"'
        - schema:
            type: string
          in: query
          name: customerName
          description: Query by invoice B2B Edition company name
        - schema:
            type: string
          in: query
          name: customerId
          description: Query by invoice B2B Edition company id
        - schema:
            type: array
            enum:
              - 0 is open
              - 1 is partial
              - 2 is completed
            example: '[0, 1]'
          in: query
          name: status
          description: Query by invoice status
        - schema:
            type: string
          in: query
          name: beginDateAt
          description: 'Query by the created time period, with the "endDateAt" parameter'
        - schema:
            type: string
          in: query
          name: endDateAt
          description: 'Query by the created time period, with the "beginDateAt" parameter'
        - schema:
            type: array
          in: query
          name: externalId
          description: Query by the invoice external ID
      tags:
        - Invoice
      x-internal: true
  /invoices/export:
    get:
      summary: Export invoices
      tags:
        - Invoice
      operationId: get-invoices-export
      description: export invoices
      parameters:
        - schema:
            type: string
          in: header
          name: authToken
          description: API Token
          required: true
        - schema:
            type: number
          in: query
          name: offset
        - schema:
            type: number
          in: query
          name: limit
        - schema:
            type: string
            enum:
              - DESC
              - ASC
            example: DESC
          in: query
          name: orderBy
          description: '"DESC" or "ASC"'
        - schema:
            type: string
            enum:
              - invoiceNumber
              - createdAt
              - customerId
              - externalCustomerId
              - dueDate
              - updatedAt
              - isPendingPayment
              - openBalance
              - originalBalance
              - status
            example: invoiceNumber
          in: query
          name: sortBy
          description: Sort by the field value
        - schema:
            type: string
            enum:
              - invoiceNumber
              - type
              - orderNumber
              - purchaseOrderNumber
              - customerId
              - externalCustomerId
            example: invoiceNumber
          in: query
          name: searchBy
          description: Filter by a field
        - schema:
            type: string
          in: query
          name: q
          description: 'Keyword queries are performed on fields corresponding to the value of "searchBy" or, if "searchBy" is empty, on all fields supported by "searchBy"'
        - schema:
            type: string
          in: query
          name: customerName
          description: Query by invoice B2B Edition company name
        - schema:
            type: string
          in: query
          name: customerId
          description: Query by invoice B2B Edition company id
        - schema:
            type: array
            enum:
              - 0 is open
              - 1 is partial
              - 2 is completed
            example: '[0, 1]'
          in: query
          name: status
          description: Query by invoice status
        - schema:
            type: string
          in: query
          name: beginDateAt
          description: 'Query by the created time period, with the "endDateAt" parameter'
        - schema:
            type: string
          in: query
          name: endDateAt
          description: 'Query by the created time period, with the "beginDateAt" parameter'
      responses:
        '200':
          description: 'If the request is successful, a file named "invoices.csv" is returned'
      x-internal: true
  '/invoices/{invoiceId}/download-pdf':
    parameters:
      - schema:
          type: string
        name: invoiceId
        in: path
        required: true
    get:
      summary: Download pdf file by invoice id
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                description: ''
                type: object
                properties:
                  code:
                    type: number
                  data:
                    type: object
                    properties:
                      url:
                        type: string
                        minLength: 1
                    required:
                      - url
                  meta:
                    type: object
                    properties:
                      message:
                        type: string
                        minLength: 1
                    required:
                      - message
                required:
                  - code
                  - data
                  - meta
                x-examples:
                  example-1:
                    code: 200
                    data:
                      url: 'https://s3-us-west-2.amazonaws.com/bundleb2b-v2.0-quote-staging/B3_Sandbox_Invoice_Portal_Dev:00000026.pdf'
                    meta:
                      message: SUCCESS
              examples:
                example-1:
                  value:
                    code: 200
                    data:
                      url: 'https://s3-us-west-2.amazonaws.com/bundleb2b-v2.0-quote-staging/B3_Sandbox_Invoice_Portal_Dev:00000026.pdf'
                    meta:
                      message: SUCCESS
      operationId: get-invoices-invoiceId-download-pdf
      description: Download pdf file by invoice id
      parameters:
        - schema:
            type: string
          in: header
          name: authToken
          required: true
      x-internal: true
x-internal: true
