openapi: '3.0.1'
info:
  title: Receipt
  description: BigCommerce B2B Edition Invoice Receipt
  contact: {}
  version: v3
servers:
  - url: 'https://api-b2b.bigcommerce.com/api/v3/io/ip'
security:
  - authToken: []
tags:
  - name: Receipt
    description: Receipt
components:
  securitySchemes:
    authToken:
      name: authToken
      type: apiKey
      in: header
  responses:
    '404':
      description: Example response
      content:
        application/json:
          schema:
            description: ''
            type: object
            properties:
              code:
                type: number
              data:
                type: object
                properties:
                  errMsg:
                    type: string
                    minLength: 1
                required:
                  - errMsg
              meta:
                type: object
                properties:
                  message:
                    type: string
                    minLength: 1
                required:
                  - message
            required:
              - code
              - data
              - meta
            x-examples:
              example-1:
                code: 404
                data:
                  errMsg: Receipt does not exist
                meta:
                  message: Not Found Error
          examples:
            example-1:
              value:
                code: 404
                data:
                  errMsg: Receipt does not exist
                meta:
                  message: Not Found Error
paths:
  /receipts:
    get:
      summary: Get receipts
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                description: ''
                type: object
                x-examples:
                  example-1:
                    code: 200
                    data:
                      - id: 101
                        createdAt: 1635932127
                        updatedAt: 1635932127
                        storeHash: rtmh8fqr05
                        customerId: '6041'
                        externalId: null
                        externalCustomerId: null
                        payerName: Check
                        payerCustomerId: '6041'
                        details:
                          paymentDetails:
                            memo: k
                        transactionType: Paid
                        paymentType: Offline
                        referenceNumber: k
                        paymentId: 117
                        total:
                          code: GBP
                          value: '0.7800'
                      - id: 100
                        createdAt: 1634785181
                        updatedAt: 1634785181
                        storeHash: rtmh8fqr05
                        customerId: '6046'
                        externalId: null
                        externalCustomerId: null
                        payerName: Check
                        payerCustomerId: '6046'
                        details:
                          paymentDetails:
                            memo: '1'
                        transactionType: Paid
                        paymentType: Offline
                        referenceNumber: '1'
                        paymentId: 116
                        total:
                          code: USD
                          value: '1.0000'
                    meta:
                      pagination:
                        totalCount: 2
                        offset: 0
                        limit: 10
                      message: SUCCESS
                properties:
                  code:
                    type: number
                  data:
                    type: array
                    uniqueItems: true
                    minItems: 1
                    items:
                      type: object
                      properties:
                        id:
                          type: number
                        createdAt:
                          type: number
                        updatedAt:
                          type: number
                        storeHash:
                          type: string
                          minLength: 1
                        customerId:
                          type: string
                          minLength: 1
                        externalId:
                          type: string
                          nullable: true
                        externalCustomerId:
                          type: string
                          nullable: true
                        payerName:
                          type: string
                          minLength: 1
                        payerCustomerId:
                          type: string
                          minLength: 1
                        details:
                          type: object
                          properties:
                            paymentDetails:
                              type: object
                              required:
                                - memo
                              properties:
                                memo:
                                  type: string
                                  minLength: 1
                          required:
                            - paymentDetails
                        transactionType:
                          type: string
                          minLength: 1
                        paymentType:
                          type: string
                          minLength: 1
                        referenceNumber:
                          type: string
                          minLength: 1
                        paymentId:
                          type: number
                        total:
                          type: object
                          properties:
                            code:
                              type: string
                              minLength: 1
                            value:
                              type: string
                              minLength: 1
                          required:
                            - code
                            - value
                      required:
                        - id
                        - createdAt
                        - updatedAt
                        - storeHash
                        - customerId
                        - payerName
                        - payerCustomerId
                        - transactionType
                        - paymentType
                        - referenceNumber
                        - paymentId
                  meta:
                    type: object
                    required:
                      - pagination
                      - message
                    properties:
                      pagination:
                        type: object
                        required:
                          - totalCount
                          - offset
                          - limit
                        properties:
                          totalCount:
                            type: number
                          offset:
                            type: number
                          limit:
                            type: number
                      message:
                        type: string
                        minLength: 1
                required:
                  - code
                  - data
                  - meta
              examples:
                example-1:
                  value:
                    code: 200
                    data:
                      - id: 85
                        createdAt: 1630658187
                        updatedAt: 1630658187
                        storeHash: 1i6zpxpe3g
                        customerId: '5485'
                        externalId: ''
                        externalCustomerId: ''
                        payerName: k Admin
                        payerCustomerId: '5485'
                        details:
                          paymentDetails:
                            memo: ''
                        transactionType: Paid
                        paymentType: Visa ending in 1111
                        referenceNumber: '375026'
                        paymentId: 92
                        total:
                          code: USD
                          value: '122.9500'
                      - id: 84
                        createdAt: 1630638069
                        updatedAt: 1630638069
                        storeHash: 1i6zpxpe3g
                        customerId: '5707'
                        externalId: ''
                        externalCustomerId: ''
                        payerName: Cash
                        payerCustomerId: '5707'
                        details:
                          paymentDetails:
                            memo: test
                        transactionType: Paid
                        paymentType: Offline
                        referenceNumber: test
                        paymentId: 91
                        total:
                          code: CNY
                          value: '0.8900'
                    meta:
                      pagination:
                        totalCount: 2
                        offset: 0
                        limit: 10
                      message: SUCCESS
      operationId: get-ip-receipts
      parameters:
        - schema:
            type: integer
            exclusiveMinimum: true
            minimum: 0
          in: query
          name: offset
          description: 'Pagination offset default: 0'
          style: form
        - schema:
            type: integer
            default: 10
            minimum: 1
            maximum: 250
          in: query
          name: limit
          description: 'Pagination limit default: 10'
        - schema:
            type: string
            default: DESC
            enum:
              - DESC
              - ASC
          in: query
          name: orderBy
          description: "Allow: 'DESC', 'ASC'"
        - schema:
            type: string
            default: createdAt
            enum:
              - '"customerId"'
              - '"externalCustomerId"'
              - '"paymentId"'
              - '"total"'
              - '"transactionType"'
              - '"referenceNumber"'
              - '"createdAt"'
              - '"updatedAt"'
          in: query
          name: sortBy
          description: The response sorted by which field
        - schema:
            type: string
          in: query
          name: q
          description: 'Keyword queries are performed on fields corresponding to the value of "searchBy" or, if "searchBy" is empty, on all fields supported by "searchBy"'
        - schema:
            type: string
            enum:
              - payerName
              - referenceNumber
              - customerId
              - externalId
              - externalCustomerId
          in: query
          name: searchBy
          description: The response search by which field
        - schema:
            type: array
            enum:
              - 0
              - 1
              - 2
              - 3
              - 4
          in: query
          name: 'paymentStatus[]'
          description: "Payment processing status. 0 means ‘Incomplete’ status, 1 means ‘Awaiting Processing’ status, 2 means ‘Processing’ status, 3 means ‘Completed’ status, 4 means ‘Refunded' status"
      description: 'Get receipts, with pagination data'
      tags:
        - Receipt
  '/receipts/{receiptId}':
    parameters:
      - schema:
          type: string
        name: receiptId
        in: path
        required: true
        description: The unique id of receipt
    get:
      summary: Get a receipt
      tags:
        - Receipt
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                description: ''
                type: object
                x-examples:
                  example-1:
                    code: 200
                    data:
                      id: 101
                      createdAt: 1635932127
                      updatedAt: 1635932127
                      storeHash: rtmh8fqr05
                      customerId: '6041'
                      externalId: null
                      externalCustomerId: null
                      payerName: Check
                      payerCustomerId: '6041'
                      details:
                        paymentDetails:
                          memo: k
                      transactionType: Paid
                      paymentType: Offline
                      referenceNumber: k
                      paymentId: 117
                      total:
                        code: GBP
                        value: '0.7800'
                    meta:
                      message: SUCCESS
                properties:
                  code:
                    type: number
                  data:
                    type: object
                    required:
                      - id
                      - createdAt
                      - updatedAt
                      - storeHash
                      - customerId
                      - externalId
                      - externalCustomerId
                      - payerName
                      - payerCustomerId
                      - details
                      - transactionType
                      - paymentType
                      - referenceNumber
                      - paymentId
                      - total
                    properties:
                      id:
                        type: number
                      createdAt:
                        type: number
                      updatedAt:
                        type: number
                      storeHash:
                        type: string
                        minLength: 1
                      customerId:
                        type: string
                        minLength: 1
                      externalId:
                        type: string
                        nullable: true
                      externalCustomerId:
                        type: string
                        nullable: true
                      payerName:
                        type: string
                        minLength: 1
                      payerCustomerId:
                        type: string
                        minLength: 1
                      details:
                        type: object
                        required:
                          - paymentDetails
                        properties:
                          paymentDetails:
                            type: object
                            required:
                              - memo
                            properties:
                              memo:
                                type: string
                                minLength: 1
                      transactionType:
                        type: string
                        minLength: 1
                      paymentType:
                        type: string
                        minLength: 1
                      referenceNumber:
                        type: string
                        minLength: 1
                      paymentId:
                        type: number
                      total:
                        type: object
                        required:
                          - code
                          - value
                        properties:
                          code:
                            type: string
                            minLength: 1
                          value:
                            type: string
                            minLength: 1
                  meta:
                    type: object
                    required:
                      - message
                    properties:
                      message:
                        type: string
                        minLength: 1
                required:
                  - code
                  - data
                  - meta
              examples:
                example-1:
                  value:
                    code: 200
                    data:
                      id: 83
                      createdAt: 1630570416
                      updatedAt: 1630570416
                      storeHash: 1i6zpxpe3g
                      customerId: '5707'
                      externalId: ''
                      externalCustomerId: ''
                      payerName: Cash
                      payerCustomerId: '5707'
                      details:
                        paymentDetails:
                          memo: test
                      transactionType: Paid
                      paymentType: Offline
                      referenceNumber: test
                      paymentId: 90
                      total:
                        code: CNY
                        value: '1.2000'
                    meta:
                      message: SUCCESS
        '404':
          $ref: '#/components/responses/404'
      operationId: get-ip-receipts-receiptId
      description: Get a receipt detail
    delete:
      summary: Delete a receipt
      tags:
        - Receipt
      operationId: delete-ip-receipts-receiptId
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: number
                    description: Response code of success request
                  data:
                    type: object
                    properties:
                      id:
                        type: integer
                        description: The uniqe receipt id
                  meta:
                    type: object
                    properties:
                      message:
                        type: string
                        description: Response message of request
              examples:
                example-1:
                  value:
                    code: 200
                    data:
                      id: 3
                    meta:
                      message: SUCCESS
        '404':
          $ref: '#/components/responses/404'
      description: Delete a receipt
  /receipt-lines:
    get:
      summary: Get all receipt lines
      tags:
        - Receipt
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                description: ''
                type: object
                x-examples:
                  example-1:
                    code: 200
                    data:
                      - id: 114
                        createdAt: 1635932127
                        updatedAt: 1635932127
                        storeHash: rtmh8fqr05
                        customerId: '6041'
                        externalId: null
                        externalCustomerId: null
                        receiptId: 101
                        invoiceId: 141
                        amount:
                          code: GBP
                          value: '0.7800'
                        paymentStatus: 3
                        paymentType: Offline
                        invoiceNumber: '00000141'
                        paymentId: 117
                        referenceNumber: k
                        transactionType: Paid
                      - id: 113
                        createdAt: 1634785181
                        updatedAt: 1634785181
                        storeHash: rtmh8fqr05
                        customerId: '6046'
                        externalId: null
                        externalCustomerId: null
                        receiptId: 100
                        invoiceId: 134
                        amount:
                          code: USD
                          value: '1.0000'
                        paymentStatus: 3
                        paymentType: Offline
                        invoiceNumber: '00000134'
                        paymentId: 116
                        referenceNumber: '1'
                        transactionType: Paid
                    meta:
                      pagination:
                        totalCount: 2
                        offset: 0
                        limit: 10
                      message: SUCCESS
                properties:
                  code:
                    type: number
                  data:
                    type: array
                    uniqueItems: true
                    minItems: 1
                    items:
                      type: object
                      properties:
                        id:
                          type: number
                        createdAt:
                          type: number
                        updatedAt:
                          type: number
                        storeHash:
                          type: string
                          minLength: 1
                        customerId:
                          type: string
                          minLength: 1
                        externalId:
                          type: string
                          nullable: true
                        externalCustomerId:
                          type: string
                          nullable: true
                        receiptId:
                          type: number
                        invoiceId:
                          type: number
                        amount:
                          type: object
                          required:
                            - code
                            - value
                          properties:
                            code:
                              type: string
                              minLength: 1
                            value:
                              type: string
                              minLength: 1
                        paymentStatus:
                          type: number
                        paymentType:
                          type: string
                          minLength: 1
                        invoiceNumber:
                          type: string
                          minLength: 1
                        paymentId:
                          type: number
                        referenceNumber:
                          type: string
                          minLength: 1
                        transactionType:
                          type: string
                          minLength: 1
                      required:
                        - id
                        - createdAt
                        - updatedAt
                        - storeHash
                        - customerId
                        - externalId
                        - externalCustomerId
                        - receiptId
                        - invoiceId
                        - amount
                        - paymentStatus
                        - paymentType
                        - invoiceNumber
                        - paymentId
                        - referenceNumber
                        - transactionType
                  meta:
                    type: object
                    required:
                      - pagination
                      - message
                    properties:
                      pagination:
                        type: object
                        required:
                          - totalCount
                          - offset
                          - limit
                        properties:
                          totalCount:
                            type: number
                          offset:
                            type: number
                          limit:
                            type: number
                      message:
                        type: string
                        minLength: 1
                required:
                  - code
                  - data
                  - meta
              examples:
                example-1:
                  value:
                    code: 200
                    data:
                      - id: 95
                        createdAt: 1630658187
                        updatedAt: 1630658187
                        storeHash: 1i6zpxpe3g
                        customerId: '5485'
                        externalId: ''
                        externalCustomerId: ''
                        receiptId: 85
                        invoiceId: 38
                        amount:
                          code: USD
                          value: '122.9500'
                        paymentStatus: 1
                        paymentType: Visa ending in 1111
                        invoiceNumber: '00000038'
                        paymentId: 92
                        referenceNumber: '375026'
                        transactionType: Paid
                      - id: 94
                        createdAt: 1630638069
                        updatedAt: 1630638069
                        storeHash: 1i6zpxpe3g
                        customerId: '5707'
                        externalId: ''
                        externalCustomerId: ''
                        receiptId: 84
                        invoiceId: 14
                        amount:
                          code: CNY
                          value: '0.0900'
                        paymentStatus: 3
                        paymentType: Offline
                        invoiceNumber: '00000014'
                        paymentId: 91
                        referenceNumber: test
                        transactionType: Paid
                    meta:
                      pagination:
                        totalCount: 2
                        offset: 0
                        limit: 10
                      message: SUCCESS
      operationId: get-ip-receipt-lines
      parameters:
        - schema:
            type: integer
            minimum: 0
          in: query
          name: offset
          description: 'Pagination offset default: 0'
        - schema:
            type: integer
            minimum: 1
            maximum: 250
            default: 10
          in: query
          name: limit
          description: 'Pagination limit default: 10'
        - schema:
            type: string
            enum:
              - DESC
              - ASC
            default: DESC
          in: query
          name: orderBy
          description: "Allow: 'DESC', 'ASC'"
        - schema:
            type: array
            enum:
              - 0
              - 1
              - 2
              - 3
              - 4
          in: query
          name: 'paymentStatus[]'
          description: "Payment processing status. 0 means ‘Incomplete’ status, 1 means ‘Awaiting Processing’ status, 2 means ‘Processing’ status, 3 means ‘Completed’ status, 4 means ‘Refunded' status"
        - schema:
            type: string
          in: query
          name: q
          description: 'Keyword queries are performed on fields corresponding to the value of "searchBy" or, if "searchBy" is empty, on all fields supported by "searchBy"'
        - schema:
            type: string
            enum:
              - customerId
              - externalId
              - externalCustomerId
              - payerName
              - payerCustomerId
              - referenceNumber
              - invoiceId
          in: query
          name: searchBy
          description: The response search by which field
        - schema:
            type: string
            default: createdAt
            enum:
              - '"customerId"'
              - '"externalCustomerId"'
              - '"receiptId"'
              - '"invoiceId"'
              - '"amount"'
              - '"createdAt"'
              - '"updatedAt"'
          in: query
          name: sortBy
          description: The response sorted by which field
      description: 'Get all receipt lines, with pagination data'
  '/receipts/{receiptId}/lines':
    get:
      summary: Get lines of a receipt
      tags:
        - Receipt
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                description: ''
                type: object
                x-examples:
                  example-1:
                    code: 200
                    data:
                      - id: 114
                        createdAt: 1635932127
                        updatedAt: 1635932127
                        storeHash: rtmh8fqr05
                        customerId: '6041'
                        externalId: null
                        externalCustomerId: null
                        receiptId: 101
                        invoiceId: 141
                        amount:
                          code: GBP
                          value: '0.7800'
                        paymentStatus: 3
                        paymentType: Offline
                        invoiceNumber: '00000141'
                        paymentId: 117
                        referenceNumber: k
                        transactionType: Paid
                    meta:
                      pagination:
                        totalCount: 1
                        offset: 0
                        limit: 10
                      message: SUCCESS
                properties:
                  code:
                    type: number
                  data:
                    type: array
                    uniqueItems: true
                    minItems: 1
                    items:
                      type: object
                      properties:
                        id:
                          type: number
                        createdAt:
                          type: number
                        updatedAt:
                          type: number
                        storeHash:
                          type: string
                          minLength: 1
                        customerId:
                          type: string
                          minLength: 1
                        externalId:
                          type: string
                          nullable: true
                        externalCustomerId:
                          type: string
                          nullable: true
                        receiptId:
                          type: number
                        invoiceId:
                          type: number
                        amount:
                          type: object
                          required:
                            - code
                            - value
                          properties:
                            code:
                              type: string
                              minLength: 1
                            value:
                              type: string
                              minLength: 1
                        paymentStatus:
                          type: number
                        paymentType:
                          type: string
                          minLength: 1
                        invoiceNumber:
                          type: string
                          minLength: 1
                        paymentId:
                          type: number
                        referenceNumber:
                          type: string
                          minLength: 1
                        transactionType:
                          type: string
                          minLength: 1
                      required:
                        - id
                        - createdAt
                        - updatedAt
                        - storeHash
                        - customerId
                        - externalId
                        - externalCustomerId
                        - receiptId
                        - invoiceId
                        - amount
                        - paymentStatus
                        - paymentType
                        - invoiceNumber
                        - paymentId
                        - referenceNumber
                        - transactionType
                  meta:
                    type: object
                    required:
                      - pagination
                      - message
                    properties:
                      pagination:
                        type: object
                        required:
                          - totalCount
                          - offset
                          - limit
                        properties:
                          totalCount:
                            type: number
                          offset:
                            type: number
                          limit:
                            type: number
                      message:
                        type: string
                        minLength: 1
                required:
                  - code
                  - data
                  - meta
              examples:
                example-1:
                  value:
                    code: 200
                    data:
                      - id: 92
                        createdAt: 1630570416
                        updatedAt: 1630570416
                        storeHash: 1i6zpxpe3g
                        customerId: '5707'
                        externalId: ''
                        externalCustomerId: ''
                        receiptId: 83
                        invoiceId: 19
                        amount:
                          code: CNY
                          value: '0.7000'
                        paymentStatus: 3
                        paymentType: Offline
                        invoiceNumber: '00000019'
                        paymentId: 90
                        referenceNumber: test
                        transactionType: Paid
                      - id: 91
                        createdAt: 1630570416
                        updatedAt: 1630570416
                        storeHash: 1i6zpxpe3g
                        customerId: '5707'
                        externalId: ''
                        externalCustomerId: ''
                        receiptId: 83
                        invoiceId: 22
                        amount:
                          code: CNY
                          value: '0.5000'
                        paymentStatus: 3
                        paymentType: Offline
                        invoiceNumber: '00000022'
                        paymentId: 90
                        referenceNumber: test
                        transactionType: Paid
                    meta:
                      pagination:
                        totalCount: 2
                        offset: 0
                        limit: 10
                      message: SUCCESS
        '404':
          $ref: '#/components/responses/404'
      operationId: get-ip-lines-of-receipt
      parameters:
        - schema:
            type: integer
            minimum: 0
          in: query
          name: offset
          description: 'Pagination offset default: 0'
        - schema:
            type: integer
            minimum: 1
            maximum: 250
            default: 10
          in: query
          name: limit
          description: 'Pagination limit default: 10'
        - schema:
            type: string
            enum:
              - DESC
              - ASC
            default: DESC
          in: query
          name: orderBy
          description: "Allow: 'DESC', 'ASC'"
        - schema:
            type: array
            enum:
              - 0
              - 1
              - 2
              - 3
              - 4
          in: query
          name: 'paymentStatus[]'
          description: "Payment processing status. 0 means ‘Incomplete’ status, 1 means ‘Awaiting Processing’ status, 2 means ‘Processing’ status, 3 means ‘Completed’ status, 4 means ‘Refunded' status"
        - schema:
            type: string
          in: query
          name: q
          description: 'Keyword queries are performed on fields corresponding to the value of "searchBy" or, if "searchBy" is empty, on all fields supported by "searchBy"'
        - schema:
            type: string
            enum:
              - customerId
              - externalId
              - externalCustomerId
              - payerName
              - payerCustomerId
              - referenceNumber
              - invoiceId
          in: query
          name: searchBy
          description: The response search by which field
        - schema:
            type: string
            default: createdAt
            enum:
              - '"customerId"'
              - '"externalCustomerId"'
              - '"receiptId"'
              - '"invoiceId"'
              - '"amount"'
              - '"createdAt"'
              - '"updatedAt"'
          in: query
          name: sortBy
          description: The response sorted by which field
      description: 'Get lines of a receipt, with pagination data'
    parameters:
      - schema:
          type: string
        name: receiptId
        in: path
        required: true
        description: The unique id of receipt
  '/receipts/{receiptId}/lines/{receiptLineId}':
    parameters:
      - schema:
          type: string
        name: receiptId
        in: path
        required: true
        description: The unique id of receipt
      - schema:
          type: string
        name: receiptLineId
        in: path
        required: true
        description: The unique id of receipt line
    get:
      summary: Get a receipt line detail
      tags:
        - Receipt
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                description: ''
                type: object
                x-examples:
                  example-1:
                    code: 200
                    data:
                      id: 114
                      createdAt: 1635932127
                      updatedAt: 1635932127
                      storeHash: rtmh8fqr05
                      customerId: '6041'
                      externalId: null
                      externalCustomerId: null
                      receiptId: 101
                      invoiceId: 141
                      amount:
                        code: GBP
                        value: '0.7800'
                      paymentStatus: 3
                      paymentType: Offline
                      invoiceNumber: '00000141'
                      paymentId: 117
                      referenceNumber: k
                      transactionType: Paid
                    meta:
                      message: SUCCESS
                properties:
                  code:
                    type: number
                  data:
                    type: object
                    required:
                      - id
                      - createdAt
                      - updatedAt
                      - storeHash
                      - customerId
                      - externalId
                      - externalCustomerId
                      - receiptId
                      - invoiceId
                      - amount
                      - paymentStatus
                      - paymentType
                      - invoiceNumber
                      - paymentId
                      - referenceNumber
                      - transactionType
                    properties:
                      id:
                        type: number
                      createdAt:
                        type: number
                      updatedAt:
                        type: number
                      storeHash:
                        type: string
                        minLength: 1
                      customerId:
                        type: string
                        minLength: 1
                      externalId:
                        type: string
                        nullable: true
                      externalCustomerId:
                        type: string
                        nullable: true
                      receiptId:
                        type: number
                      invoiceId:
                        type: number
                      amount:
                        type: object
                        required:
                          - code
                          - value
                        properties:
                          code:
                            type: string
                            minLength: 1
                          value:
                            type: string
                            minLength: 1
                      paymentStatus:
                        type: number
                      paymentType:
                        type: string
                        minLength: 1
                      invoiceNumber:
                        type: string
                        minLength: 1
                      paymentId:
                        type: number
                      referenceNumber:
                        type: string
                        minLength: 1
                      transactionType:
                        type: string
                        minLength: 1
                  meta:
                    type: object
                    required:
                      - message
                    properties:
                      message:
                        type: string
                        minLength: 1
                required:
                  - code
                  - data
                  - meta
              examples:
                example-1:
                  value:
                    code: 200
                    data:
                      id: 92
                      createdAt: 1630570416
                      updatedAt: 1630570416
                      storeHash: 1i6zpxpe3g
                      customerId: '5707'
                      externalId: ''
                      externalCustomerId: ''
                      receiptId: 83
                      invoiceId: 19
                      amount:
                        code: CNY
                        value: '0.7000'
                      paymentStatus: 3
                      paymentType: Offline
                      invoiceNumber: '00000019'
                      paymentId: 90
                      referenceNumber: test
                      transactionType: Paid
                    meta:
                      message: SUCCESS
      operationId: get-ip-receipts-receiptId-lines-receiptLineId
      description: Get a receipt line detail
    delete:
      summary: Delete a receipt line
      tags:
        - Receipt
      operationId: delete-ip-receipts-receiptId-lines-receiptLineId
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: number
                    description: Response code of success request
                  data:
                    type: object
                    properties:
                      id:
                        type: integer
                        description: The unique id of receipt line
                  meta:
                    type: object
                    properties:
                      message:
                        type: string
                        description: Response message of request
              examples:
                example-1:
                  value:
                    code: 200
                    data:
                      id: 92
                    meta:
                      message: SUCCESS
      description: Delete a receipt line
