openapi: '3.0.0'
info:
  version: ''
  title: Payment Processing
  description: 'Process payments using payment instrument such as credit card. See [Payments Overview](/api-docs/store-management/payment-processing) for more information.'
  termsOfService: 'https://www.bigcommerce.com/terms'
  contact:
    name: BigCommerce
    url: 'https://www.bigcommerce.com'
    email: support@bigcommerce.com
tags:
  - name: Accepted Methods
  - name: Access Tokens
  - name: Process Payment
servers:
  - url: 'https://api.bigcommerce.com/stores/{store_hash}/v3'
    variables:
      store_hash:
        default: store_hash
        description: Permanent ID of the BigCommerce store.
    description: BigCommerce API Gateway
  - url: 'https://payments.bigcommerce.com'
    description: BigCommerce Payments Gateway
paths:
  '/payments':
    post:
      summary: Process Payment
      tags:
        - Process Payment
      operationId: PaymentsPost
      description: 'Process payments for an order. See [Payment Processing](/api-docs/store-management/payment-processing) for more information.'
      servers:
        - url: 'https://payments.bigcommerce.com'
          description: BigCommerce Payments Gateway
      security:
        - BearerPAT: []
      parameters:
        - $ref: '#/components/parameters/AcceptPaymentResponse'
        - $ref: '#/components/parameters/ContentType'
      requestBody:
        content:
          application/json:
            schema:
              title: Payment Request
              type: object
              properties:
                payment:
                  title: Payment
                  type: object
                  required:
                    - instrument
                    - payment_method_id
                  properties:
                    instrument:
                      anyOf:
                        - $ref: '#/components/schemas/Card'
                        - $ref: '#/components/schemas/StoredCard'
                        - $ref: '#/components/schemas/StoredPayPalAccount'
                        - $ref: '#/components/schemas/GiftCertificate'
                        - $ref: '#/components/schemas/StoreCredit'
                    payment_method_id:
                      description: Identifier for payment method that will be used for this payment and `id` from the Get Accepted Payment Methods API
                      type: string
                      minLength: 1
                    save_instrument:
                      type: boolean
                      description: 'To use `save_instrument`, configure the payment gateway to accept stored cards.'
              required:
                - payment
            examples:
              Card:
                value:
                  payment:
                    instrument:
                      type: card
                      cardholder_name: string
                      number: string
                      expiry_month: 1
                      expiry_year: 0
                      verification_value: stri
                      issue_month: 1
                      issue_year: 0
                      issue_number: 0
                    payment_method_id: string
              Stored Card:
                value:
                  payment:
                    instrument:
                      type: stored_card
                      token: 8cdf7b6ea1b27119463bf9e5106639618cc77a9adc49f0069ca8b756cc15caee
                      verification_value: '1142'
                    payment_method_id: adyenv2.scheme
                    save_instrument: true
              Stored PayPal Account:
                value:
                  payment:
                    instrument:
                      type: stored_paypal_account
                      token: 2c129313bcffe4501ec5fa2764c8c16320e38c7ba9e8cdf95583b541bb05ad91
                    payment_method_id: braintree.paypal
              Gift Certificate:
                value:
                  payment:
                    instrument:
                      type: gift_certificate
                      gift_certificate_code: ABC-DEF-GXX
                    payment_method_id: bigcommerce.gift_certificate
              Store Credit:
                value:
                  payment:
                    instrument:
                      type: store_credit
                    payment_method_id: bigcommerce.store_credit
        required: true
        x-examples:
          application/json:
            payment:
              instrument: {}
              payment_method_id: Lorem in
              amount: 81505146
              currency_code: NYE
          Payment Access Token: |-
            curl -X POST \
              https://payments.bigcommerce.com/stores/{store_hash}/payments \
              -H 'Accept: application/vnd.bc.v1+json' \
              -H 'Authorization: PAT eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE1NsdfasftIsIm5iZiI6MTU1MTM5MDU0MiwiaXNzIjoicGF5bWVudHMuYmlnY29tbWVyY2UuY29tIiwic3ViIjoianJhaDZnbW4iLCJqdGkiOiI3Nzg3ZmU1Zi01OWJmLTQ3ZWMtYTFmZC00ZDQ3ZTkwNjFlNWMiLCJpYXQiOjE1NTEzOTA1NDIsImRhdGEiOnsic3RvcmVfaWQiOjEwMjU2NDYsIm9yZGVyX2lkIjoyMTUsImFtb3VudCI6OTgwMCwiY3VycmVuY3kiOiJVU0QifX0.WbR90d8m4gn8wK7kPMDEoVq8B0hHC5Ul5H4Hpqq6Yvo' \
              -H 'Content-Type: application/json' \
          Vaulted Card:
            payment:
              instrument:
                type: stored_card
                token: vaulted instrument token
                verification_value: '123'
              payment_method_id: stripe.card
              save_instrument: true
          Credit Card: |-
            {
              "payment": {
                "instrument": {
                  "type": "card",
                  "number": "4111111111111111",
                  "cardholder_name": "BP",
                  "expiry_month": 12,
                  "expiry_year": 2020,
                  "verification_value": "411"
                },
                "payment_method_id": "authorizenet.card",
                 "save_instrument": true
              }
            }
        description: ''
      responses:
        '202':
          description: Payment has been successfully processed
          content:
            application/json:
              schema:
                title: Success Payment Response
                type: object
                properties:
                  id:
                    description: Identifier for this transaction
                    type: string
                  transaction_type:
                    title: Transaction Type
                    description: Transaction type for this payment
                    example: authorization
                    type: string
                    enum:
                      - authorization
                      - purchase
                  status:
                    type: string
                    title: Status
                    description: Status to indicate a success response
                    enum:
                      - success
                      - pending
              examples:
                response:
                  value:
                    id: 227d9e1e-94f8-408c-95a5-f97b30592eb7
                    transaction_type: authorization
                    status: pending
        '400':
          description: Payment request has been rejected due to malformed request
          content:
            application/json:
              schema:
                title: Error Payment Response
                type: object
                properties:
                  status:
                    description: HTTP status code
                    type: integer
                    format: int32
                  title:
                    description: Short summary describing the particular error
                    type: string
                  detail:
                    description: Detailed summary describing the particular error
                    type: string
                  type:
                    description: Reference that identifies the particular error
                    type: string
                  code:
                    description: Code representing the particular error
                    type: integer
                    format: int32
                  errors:
                    description: ''
                    type: object
                    additionalProperties:
                      type: string
                required:
                  - status
                  - title
                  - type
        '401':
          description: Valid authentication required
          content:
            application/json:
              schema:
                title: Error Payment Response
                type: object
                properties:
                  status:
                    description: HTTP status code
                    type: integer
                    format: int32
                  title:
                    description: Short summary describing the particular error
                    type: string
                  detail:
                    description: Detailed summary describing the particular error
                    type: string
                  type:
                    description: Reference that identifies the particular error
                    type: string
                  code:
                    description: Code representing the particular error
                    type: integer
                    format: int32
                  errors:
                    description: ''
                    type: object
                    additionalProperties:
                      type: string
                required:
                  - status
                  - title
                  - type
        '422':
          description: 'Payment request has been rejected due to missing, invalid data or declined by payment provider'
          content:
            application/json:
              schema:
                title: Error Payment Response
                type: object
                properties:
                  status:
                    description: HTTP status code
                    type: integer
                    format: int32
                  title:
                    description: Short summary describing the particular error
                    type: string
                  detail:
                    description: Detailed summary describing the particular error
                    type: string
                  type:
                    description: Reference that identifies the particular error
                    type: string
                  code:
                    description: Code representing the particular error
                    type: integer
                    format: int32
                  errors:
                    description: ''
                    type: object
                    additionalProperties:
                      type: string
                required:
                  - status
                  - title
                  - type
        default:
          description: Internal server error
          content:
            application/json:
              schema:
                title: Error Payment Response
                type: object
                properties:
                  status:
                    description: HTTP status code
                    type: integer
                    format: int32
                  title:
                    description: Short summary describing the particular error
                    type: string
                  detail:
                    description: Detailed summary describing the particular error
                    type: string
                  type:
                    description: Reference that identifies the particular error
                    type: string
                  code:
                    description: Code representing the particular error
                    type: integer
                    format: int32
                  errors:
                    description: ''
                    type: object
                    additionalProperties:
                      type: string
                required:
                  - status
                  - title
                  - type
  '/payments/access_tokens':
    parameters:
      - $ref: '#/components/parameters/Accept'
    post:
      description: |-
        This endpoint provides the capability to create a payment access token. The payment access token is required when making request to Payment API for submitting payment for an order.

        After the token is created, use the token to [Process Payments](/docs/rest-payments/processing/process-payment#process-payment).

        **Required Fields**
        * order_id
      summary: Create Payment Access Token
      tags:
        - Access Tokens
      operationId: PaymentsAccessTokensPost
      servers:
        - url: 'https://api.bigcommerce.com/stores/{store_hash}/v3'
          variables:
            store_hash:
              default: store_hash
              description: Permanent ID of the BigCommerce store.
          description: BigCommerce API Gateway
      security:
        - X-Auth-Token: []
      deprecated: false
      parameters:
        - $ref: '#/components/parameters/ContentType'
      requestBody:
        content:
          application/json:
            schema:
              title: Payment Access Token Request
              type: object
              properties:
                order:
                  $ref: '#/components/schemas/Order'
              required:
                - order
            examples:
              example-1:
                value:
                  order:
                    id: 1
                    is_recurring: false
        required: true
        x-examples:
          application/json:
            order:
              id: 44796008
              is_recurring: true
          Example:
            order:
              id: 182
      responses:
        '201':
          description: Payment access token has been successfully created
          headers: {}
          content:
            application/json:
              schema:
                title: Payments Access Tokens Response
                type: object
                properties:
                  data:
                    title: Payment Access Token
                    type: object
                    properties:
                      id:
                        description: Payment access token. This token is required in subsequent payment request to Payment API endpoint.
                        type: string
                        minLength: 1
                    required:
                      - id
                  meta:
                    type: object
                    properties: {}
                    additionalProperties: true
                    description: Response metadata.
              examples:
                example-1:
                  value:
                    data:
                      id: eyJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2MTUyNTA3NTksIm5iZiI6MTYxNTI0Nz E1OSwiaXNzIjoicGF5bWVudHMuYmlnY29tbWVyY2UuY29tIiwic3ViIjoieHNsM3 JoZGYzNiIsImp0aSI6IjNhOGE3NTJjLTBmNWQtNDNmNS05MzdjLTRhMTYzODBlMW YwZCIsImlhdCI6MTYxNTI0NzE1OSwiZGF0YSI6eyJzdG9yZV9pZCI6IjEwMDEzMz YzMjQiLCJvcmRlcl9pZCI6IjE2NiIsImFtb3VudCI6NDU3OTAsImN1cnJlbmN5Ij oiVVNEIn19.dpCDgOfbNrz095VARY20yYBRTOuq-W1F0ETTgf1Zhbs
                    meta: {}
        '400':
          description: Request has been rejected
          content:
            application/json:
              schema:
                title: ErrorResponse
                type: object
                properties:
                  status:
                    description: HTTP status code
                    type: integer
                    format: int32
                  title:
                    description: Short summary describing the particular error
                    type: string
                  detail:
                    description: Detailed summary describing the particular error
                    type: string
                  type:
                    description: Reference that identifies the particular error
                    type: string
                  code:
                    description: Code representing the particular error
                    type: integer
                    format: int32
                  errors:
                    type: object
                    additionalProperties:
                      type: string
                required:
                  - status
                  - title
                  - type
        '401':
          description: Valid authentication required
          content:
            application/json:
              schema:
                title: ErrorResponse
                type: object
                properties:
                  status:
                    description: HTTP status code
                    type: integer
                    format: int32
                  title:
                    description: Short summary describing the particular error
                    type: string
                  detail:
                    description: Detailed summary describing the particular error
                    type: string
                  type:
                    description: Reference that identifies the particular error
                    type: string
                  code:
                    description: Code representing the particular error
                    type: integer
                    format: int32
                  errors:
                    type: object
                    additionalProperties:
                      type: string
                required:
                  - status
                  - title
                  - type
        '404':
          description: Request has been rejected due to resource not being found
          content:
            application/json:
              schema:
                title: ErrorResponse
                type: object
                properties:
                  status:
                    description: HTTP status code
                    type: integer
                    format: int32
                  title:
                    description: Short summary describing the particular error
                    type: string
                  detail:
                    description: Detailed summary describing the particular error
                    type: string
                  type:
                    description: Reference that identifies the particular error
                    type: string
                  code:
                    description: Code representing the particular error
                    type: integer
                    format: int32
                  errors:
                    type: object
                    additionalProperties:
                      type: string
                required:
                  - status
                  - title
                  - type
        '409':
          description: Request has been rejected due to conflict with the current state of the target resource
          content:
            application/json:
              schema:
                title: ErrorResponse
                type: object
                properties:
                  status:
                    description: HTTP status code
                    type: integer
                    format: int32
                  title:
                    description: Short summary describing the particular error
                    type: string
                  detail:
                    description: Detailed summary describing the particular error
                    type: string
                  type:
                    description: Reference that identifies the particular error
                    type: string
                  code:
                    description: Code representing the particular error
                    type: integer
                    format: int32
                  errors:
                    type: object
                    additionalProperties:
                      type: string
                required:
                  - status
                  - title
                  - type
        '422':
          description: Request has been rejected due to missing or invalid data
          content:
            application/json:
              schema:
                title: ErrorResponse
                type: object
                properties:
                  status:
                    description: HTTP status code
                    type: integer
                    format: int32
                  title:
                    description: Short summary describing the particular error
                    type: string
                  detail:
                    description: Detailed summary describing the particular error
                    type: string
                  type:
                    description: Reference that identifies the particular error
                    type: string
                  code:
                    description: Code representing the particular error
                    type: integer
                    format: int32
                  errors:
                    type: object
                    additionalProperties:
                      type: string
                required:
                  - status
                  - title
                  - type
        default:
          description: Internal server error
          content:
            application/json:
              schema:
                title: ErrorResponse
                type: object
                properties:
                  status:
                    description: HTTP status code
                    type: integer
                    format: int32
                  title:
                    description: Short summary describing the particular error
                    type: string
                  detail:
                    description: Detailed summary describing the particular error
                    type: string
                  type:
                    description: Reference that identifies the particular error
                    type: string
                  code:
                    description: Code representing the particular error
                    type: integer
                    format: int32
                  errors:
                    type: object
                    additionalProperties:
                      type: string
                required:
                  - status
                  - title
                  - type
  '/payments/methods':
    parameters:
      - $ref: '#/components/parameters/Accept'
    get:
      description: |-
        Returns a list of accepted payment methods based on the `order_id` or `checkout_id`.

        **Notes**
        * Use the [Create an Order](/docs/rest-management/orders#create-an-order) endpoint to generate the `order_id`.
        * Orders created will be set to incomplete order status.
        * The cart ID and checkout ID are the same.

        **Required Fields**
        * `order_id` or `checkout_id`
      summary: Get Accepted Payment Methods
      tags:
        - Accepted Methods
      operationId: PaymentsMethodsGet
      servers:
        - url: 'https://api.bigcommerce.com/stores/{store_hash}/v3'
          variables:
            store_hash:
              default: store_hash
              description: Permanent ID of the BigCommerce store.
          description: BigCommerce API Gateway
      security:
        - X-Auth-Token: []
      deprecated: false
      parameters:
        - name: order_id
          in: query
          description: Identifier for the order
          schema:
            type: integer
            format: int32
            exclusiveMinimum: false
            exclusiveMaximum: false
        - name: checkout_id
          in: query
          description: Identifier for the checkout (same as the cart ID)
          schema:
            type: string
            exclusiveMinimum: false
            exclusiveMaximum: false
      responses:
        '200':
          $ref: '#/components/responses/paymentsMethods_Resp'
        '400':
          description: Request has been rejected
          content:
            application/json:
              schema:
                title: ErrorResponse
                type: object
                properties:
                  status:
                    description: HTTP status code
                    type: integer
                    format: int32
                  title:
                    description: Short summary describing the particular error
                    type: string
                  detail:
                    description: Detailed summary describing the particular error
                    type: string
                  type:
                    description: Reference that identifies the particular error
                    type: string
                  code:
                    description: Code representing the particular error
                    type: integer
                    format: int32
                  errors:
                    type: object
                    additionalProperties:
                      type: string
                required:
                  - status
                  - title
                  - type
        '401':
          description: Valid authentication required
          content:
            application/json:
              schema:
                title: ErrorResponse
                type: object
                properties:
                  status:
                    description: HTTP status code
                    type: integer
                    format: int32
                  title:
                    description: Short summary describing the particular error
                    type: string
                  detail:
                    description: Detailed summary describing the particular error
                    type: string
                  type:
                    description: Reference that identifies the particular error
                    type: string
                  code:
                    description: Code representing the particular error
                    type: integer
                    format: int32
                  errors:
                    type: object
                    additionalProperties:
                      type: string
                required:
                  - status
                  - title
                  - type
        '404':
          description: Request has been rejected due to resource not being found
          content:
            application/json:
              schema:
                title: ErrorResponse
                type: object
                properties:
                  status:
                    description: HTTP status code
                    type: integer
                    format: int32
                  title:
                    description: Short summary describing the particular error
                    type: string
                  detail:
                    description: Detailed summary describing the particular error
                    type: string
                  type:
                    description: Reference that identifies the particular error
                    type: string
                  code:
                    description: Code representing the particular error
                    type: integer
                    format: int32
                  errors:
                    type: object
                    additionalProperties:
                      type: string
                required:
                  - status
                  - title
                  - type
        '422':
          description: Request has been rejected due to missing or invalid data
          content:
            application/json:
              schema:
                title: ErrorResponse
                type: object
                properties:
                  status:
                    description: HTTP status code
                    type: integer
                    format: int32
                  title:
                    description: Short summary describing the particular error
                    type: string
                  detail:
                    description: Detailed summary describing the particular error
                    type: string
                  type:
                    description: Reference that identifies the particular error
                    type: string
                  code:
                    description: Code representing the particular error
                    type: integer
                    format: int32
                  errors:
                    type: object
                    additionalProperties:
                      type: string
                required:
                  - status
                  - title
                  - type
        default:
          description: Internal server error
          content:
            application/json:
              schema:
                title: ErrorResponse
                type: object
                properties:
                  status:
                    description: HTTP status code
                    type: integer
                    format: int32
                  title:
                    description: Short summary describing the particular error
                    type: string
                  detail:
                    description: Detailed summary describing the particular error
                    type: string
                  type:
                    description: Reference that identifies the particular error
                    type: string
                  code:
                    description: Code representing the particular error
                    type: integer
                    format: int32
                  errors:
                    type: object
                    additionalProperties:
                      type: string
                required:
                  - status
                  - title
                  - type
components:
  parameters:
    AcceptPaymentResponse:
      name: Accept
      in: header
      schema:
        type: string
        enum:
          - 'application/vnd.bc.v1+json'
        default: 'application/vnd.bc.v1+json'
      required: true
      description: This required value must be `application/vnd.bc.v1+json`.
    Accept:
      name: Accept
      in: header
      required: true
      description: 'The [MIME type](https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/MIME_types) of the response body.'
      schema:
        type: string
        default: 'application/json'
    ContentType:
      name: Content-Type
      in: header
      required: true
      description: 'The [MIME type](https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/MIME_types) of the request body.'
      schema:
        type: string
        default: 'application/json'
  responses:
    paymentsMethods_Resp:
      description: ''
      content:
        application/json:
          schema:
            title: Payments Methods Response
            type: object
            properties:
              data:
                type: array
                items:
                  $ref: '#/components/schemas/paymentMethod_Full'
              meta: 
                type: object
                properties: {}
                additionalProperties: true
                description: Response metadata.
          examples:
            response:
              value:
                data:
                  - id: bigcommerce.gift_certificate
                    name: Gift Certificate
                    test_mode: false
                    type: gift_certificate
                    supported_instruments: []
                    stored_instruments: []
                  - id: bigcommerce.store_credit
                    name: Store Credit
                    test_mode: false
                    type: store_credit
                    supported_instruments: []
                    stored_instruments: []
                  - id: stripe.card
                    name: Stripe
                    test_mode: true
                    type: card
                    supported_instruments:
                      - instrument_type: VISA
                        verification_value_required: true
                      - instrument_type: MASTERCARD
                        verification_value_required: true
                      - instrument_type: AMEX
                        verification_value_required: true
                      - instrument_type: DISCOVER
                        verification_value_required: true
                      - instrument_type: JCB
                        verification_value_required: true
                      - instrument_type: DINERS_CLUB
                        verification_value_required: true
                      - instrument_type: STORED_CARD
                        verification_value_required: true
                    stored_instruments:
                      - type: stored_card
                        brand: VISA
                        expiry_month: 9
                        expiry_year: 2020
                        issuer_identification_number: '424242'
                        last_4: '4242'
                        token: 050a1e5c982e5905288ec5ec33f292772762033a0704f46fccb16bf1940b51ef
                        is_default: true
                meta: {}
    paymentAccessToken_Resp:
      description: ''
      content:
        application/json:
          schema:
            title: Payments Access Tokens Response
            type: object
            properties:
              data:
                $ref: '#/components/schemas/PaymentAccessToken'
  securitySchemes:
    X-Auth-Token:
      name: X-Auth-Token
      description: |-
        ### OAuth scopes

        | UI Name | Permission | Parameter |
        |:--------|:-----------|:----------|
        |  Create Payments | create | `store_payments_access_token_create` |
        |  Get Payment Methods | read-only | `store_payments_methods_read` |

        ### Authentication header
        
        | Header | Argument | Description |
        |:-------|:---------|:------------|
        | `X-Auth-Token` | `access_token` | For more about API accounts that generate `access_token`s, see our [Guide to API Accounts](/api-docs/getting-started/api-accounts). |

        ### Further reading
        
        For example requests and more information about authenticating BigCommerce APIs, see [Authentication and Example Requests](/api-docs/getting-started/authentication#x-auth-token-header-example-requests).
        
        For more about BigCommerce OAuth scopes, see our [Guide to API Accounts](/api-docs/getting-started/api-accounts#oauth-scopes).
        
        For a list of API status codes, see [API Status Codes](/api-docs/getting-started/api-status-codes).
      type: apiKey
      in: header
    BearerPAT:
      description: |-
        ### OAuth scopes

        The required scopes are granted to the `payment_access_token` upon generation.

        ### Authentication header
        
        | Header | Argument | Description |
        |:-------|:---------|:------------|
        |`Authorization`|`PAT {{PAYMENT_ACCESS_TOKEN}}`| Obtained using the Create Access Token endpoint.|

        ### Further reading
        
        For an outline of the Process Payment API call flow and more information about authenticating, see [Authentication and Example Requests](/api-docs/getting-started/authentication#bigcommerce-generated-jwts).
        
        For a list of API status codes, see [API Status Codes](/api-docs/getting-started/api-status-codes).
      type: http
      scheme: bearer
      bearerFormat: 'PAT {{PAYMENT_ACCESS_TOKEN}}'
  schemas:
    PaymentRequest:
      title: Payment Request
      type: object
      properties:
        payment:
          title: Payment
          type: object
          required:
            - instrument
            - payment_method_id
          properties:
            amount:
              description: Amount in smallest currency unit
              type: integer
              format: int32
            currency_code:
              description: Currency code
              type: string
              pattern: '^[A-Z]{3}$'
            instrument:
              description: ''
              type: object
            payment_method_id:
              description: Identifier for payment method that will be used for this payment
              type: string
              minLength: 1
      required:
        - payment
      x-internal: false
    Payment:
      title: Payment
      type: object
      properties:
        amount:
          description: Amount in smallest currency unit
          type: integer
          format: int32
        currency_code:
          description: Currency code
          type: string
          pattern: '^[A-Z]{3}$'
        instrument:
          description: ''
          type: object
        payment_method_id:
          description: Identifier for payment method that will be used for this payment
          type: string
          minLength: 1
      required:
        - instrument
        - payment_method_id
      x-internal: false
    SuccessPaymentResponse:
      title: Success Payment Response
      type: object
      properties:
        id:
          description: Identifier for this transaction
          type: string
        transaction_type:
          title: Transaction Type
          description: Transaction type for this payment
          example: authorization
          type: string
          enum:
            - authorization
            - purchase
        status:
          type: string
          title: Status
          description: Status to indicate a success response
          enum:
            - success
            - pending
      x-internal: false
    TransactionType:
      title: Transaction Type
      description: Transaction type for this payment
      example: authorization
      type: string
      enum:
        - authorization
        - purchase
      x-internal: false
    Status:
      type: string
      title: Status
      description: Status to indicate a success response
      enum:
        - success
        - pending
      x-internal: false
    ErrorPaymentResponse:
      title: Error Payment Response
      type: object
      properties:
        status:
          description: HTTP status code
          type: integer
          format: int32
        title:
          description: Short summary describing the particular error
          type: string
        detail:
          description: Detailed summary describing the particular error
          type: string
        type:
          description: Reference that identifies the particular error
          type: string
        code:
          description: Code representing the particular error
          type: integer
          format: int32
        errors:
          description: ''
          type: object
          additionalProperties:
            type: string
      required:
        - status
        - title
        - type
      x-internal: false
    Card:
      title: Card
      type: object
      x-examples:
        example-1:
          type: card
          cardholder_name: string
          number: string
          expiry_month: 1
          expiry_year: 0
          verification_value: stri
          issue_month: 1
          issue_year: 0
          issue_number: 0
      x-internal: false
      properties:
        type:
          type: string
          default: card
          example: card
          description: Type to classify this payment instrument (required)
        cardholder_name:
          type: string
          minLength: 1
          description: Cardholderʼs full name (required)
        number:
          type: string
          minLength: 1
          description: Credit card number (required)
        expiry_month:
          type: integer
          format: int32
          minimum: 1
          maximum: 12
          description: Expiry month of this card (required)
        expiry_year:
          type: integer
          format: int32
          description: Expiry year of this card (required)
        verification_value:
          type: string
          minLength: 3
          maxLength: 4
          description: Verification value of this card (CVV)
        issue_month:
          type: integer
          description: Issue month of this card
          format: int32
          minimum: 1
          maximum: 12
        issue_year:
          type: integer
          format: int32
          description: Issue year of this card
        issue_number:
          type: integer
          format: int32
          description: Issue number of this card
    StoredCard:
      title: Stored Card
      type: object
      x-internal: false
      x-examples:
        example-1:
          type: stored_card
          token: stringstringstringstringstringstringstringstringstringstringstri
          verification_value: 1142
      properties:
        type:
          description: Type to classify this payment instrument (required)
          example: stored_card
          type: string
          default: stored_card
        token:
          description: Identifier representing this stored card (required)
          type: string
          minLength: 64
          maxLength: 64
        verification_value:
          type: string
          description: Verification value of this card (CVV)
          minLength: 3
          maxLength: 4
    BasePaymentResponse:
      title: Base Payment Response
      type: object
      properties:
        id:
          description: Identifier for this transaction
          type: string
        transaction_type:
          title: Transaction Type
          description: Transaction type for this payment
          example: authorization
          type: string
          enum:
            - authorization
            - purchase
      x-internal: false
    PendingPaymentResponse:
      title: Pending Payment Response
      type: object
      properties:
        id:
          description: Identifier for this transaction
          type: string
        transaction_type:
          title: Transaction Type
          description: Transaction type for this payment
          example: authorization
          type: string
          enum:
            - authorization
            - purchase
        status:
          type: string
          title: Status
          description: Status to indicate a success response
          enum:
            - success
            - pending
      x-internal: false
    StoredPayPalAccount:
      title: StoredPayPalAccount
      type: object
      x-internal: false
      properties:
        type:
          type: string
          description: Type to classify this payment instrument (required)
          enum:
            - stored_paypal_account
        token:
          description: Identifier representing this stored PayPal account (required)
          type: string
          minLength: 64
          maxLength: 64
      x-examples:
        example-1:
          type: stored_paypal_account
          token: stringstringstringstringstringstringstringstringstringstringstri
    Order:
      title: Order
      type: object
      properties:
        id:
          description: Identifier for the order
          type: integer
          minimum: 1
          format: int32
        is_recurring:
          description: Whether this is a recurring order. If the order is recurring this field should be set to true in order to let the payment gateway know.
          example: false
          type: boolean
          default: false
      required:
        - id
      x-examples:
        example-1:
          id: 1
          is_recurring: false
      x-internal: false
    PaymentAccessTokenRequest:
      title: Payment Access Token Request
      type: object
      properties:
        order:
          title: Order
          type: object
          required:
            - id
          properties:
            id:
              description: Identifier for the order
              type: integer
              minimum: 1
              format: int32
            is_recurring:
              description: Whether this is a recurring order. If the order is recurring this field should be set to true in order to let the payment gateway know.
              example: false
              type: boolean
              default: false
      required:
        - order
      x-internal: false
    PaymentAccessToken:
      title: Payment Access Token
      type: object
      properties:
        id:
          description: Payment access token. This token is required in subsequent payment request to Payment API endpoint.
          type: string
          minLength: 1
      required:
        - id
      x-internal: false
    paymentMethodStoredInstrument:
      title: paymentMethodStoredInstrument
      type: object
      properties:
        brand:
          description: Brand of this card such as VISA or Mastercard
          type: string
          minLength: 1
        expiry_month:
          description: Expiry month of this card
          type: integer
          minimum: 1
          maximum: 12
          format: int32
        expiry_year:
          description: Expiry year of this card
          type: integer
          format: int32
        issuer_identification_number:
          description: Issuer identification number of this card. This is extracted from the card when the order is payed for.
          type: string
          minLength: 6
          maxLength: 6
        last_4:
          description: Last four numbers of this card
          type: string
          minLength: 4
          maxLength: 4
        token:
          description: A BigCommerce-generated identifier that represents the stored card.
          type: string
          minLength: 64
          maxLength: 64
        is_default:
          description: Whether this instrument is a default instrument
          example: false
          type: boolean
          default: false
        type:
          description: Type to classify this stored card
          example: stored_card
          type: string
          default: stored_card
      required:
        - brand
        - expiry_month
        - expiry_year
        - issuer_identification_number
        - last_4
        - token
        - is_default
        - type
      x-examples:
        example-1:
          brand: string
          expiry_month: 1
          expiry_year: 0
          issuer_identification_number: string
          last_4: stri
          token: stringstringstringstringstringstringstringstringstringstringstri
          is_default: false
          type: stored_card
      x-internal: false
    paymentMethod_Full:
      title: paymentMethod_Full
      type: object
      properties:
        id:
          description: Identifier for this payment method
          type: string
          minLength: 1
        name:
          description: Name of this payment method
          type: string
          minLength: 1
        stored_instruments:
          type: array
          items:
            $ref: '#/components/schemas/paymentMethodStoredInstrument'
        supported_instruments:
          type: array
          items:
            title: Supported Card Instrument
            type: object
            properties:
              instrument_type:
                title: InstrumentType
                description: Type of this instrument
                example: VISA
                type: string
                enum:
                  - VISA
                  - MASTERCARD
                  - DISCOVER
                  - AMEX
                  - DINERS_CLUB
                  - JCB
                  - DANKORT
                  - MAESTRO
                  - STORED_CARD
              verification_value_required:
                description: Whether verification value is required for payment
                type: boolean
            required:
              - instrument_type
        test_mode:
          description: Whether this payment method is on test mode
          example: false
          type: boolean
          default: false
        type:
          description: Type to classify this payment method
          example: card
          type: string
          default: card
      required:
        - id
        - name
        - supported_instruments
        - test_mode
        - type
      x-examples:
        example-1:
          id: string
          name: string
          stored_instruments:
            - brand: string
              expiry_month: 1
              expiry_year: 0
              issuer_identification_number: string
              last_4: stri
              token: stringstringstringstringstringstringstringstringstringstringstri
              is_default: false
              type: stored_card
          supported_instruments:
            - instrument_type: VISA
              verification_value_required: true
          test_mode: false
          type: card
      x-internal: false
    SupportedCardInstrument:
      title: Supported Card Instrument
      type: object
      properties:
        instrument_type:
          title: InstrumentType
          description: Type of this instrument
          example: VISA
          type: string
          enum:
            - VISA
            - MASTERCARD
            - DISCOVER
            - AMEX
            - DINERS_CLUB
            - JCB
            - DANKORT
            - MAESTRO
            - STORED_CARD
        verification_value_required:
          description: Whether verification value is required for payment
          type: boolean
      required:
        - instrument_type
      x-internal: false
    Error:
      title: Error
      type: object
      properties:
        status:
          description: HTTP status code
          type: integer
          format: int32
        title:
          description: Short summary describing the particular error
          type: string
        detail:
          description: Detailed summary describing the particular error
          type: string
        type:
          description: Reference that identifies the particular error
          type: string
        code:
          description: Code representing the particular error
          type: integer
          format: int32
      required:
        - status
        - title
        - type
      x-internal: false
    ErrorResponse:
      title: ErrorResponse
      type: object
      properties:
        status:
          description: HTTP status code
          type: integer
          format: int32
        title:
          description: Short summary describing the particular error
          type: string
        detail:
          description: Detailed summary describing the particular error
          type: string
        type:
          description: Reference that identifies the particular error
          type: string
        code:
          description: Code representing the particular error
          type: integer
          format: int32
        errors:
          type: object
          additionalProperties:
            type: string
      required:
        - status
        - title
        - type
      x-internal: false
    InstrumentType:
      title: InstrumentType
      description: Type of this instrument
      example: VISA
      type: string
      enum:
        - VISA
        - MASTERCARD
        - DISCOVER
        - AMEX
        - DINERS_CLUB
        - JCB
        - DANKORT
        - MAESTRO
        - STORED_CARD
      x-internal: false
    StoredPayPalAccountInstrument:
      title: StoredPayPalAccountInstrument
      type: object
      properties:
        email:
          type: string
          format: email
          description: Email address of this stored account
        token:
          type: string
          description: Identifier representing this stored account
          minLength: 64
          maxLength: 64
        is_default:
          type: boolean
          description: Whether this instrument is a default instrument
          default: false
        type:
          type: string
          description: Type to classify this stored account
          enum:
            - stored_paypal_account
      required:
        - email
        - token
        - is_default
        - type
      x-internal: false
    SupportedPayPalAccountInstrument:
      title: SupportedPayPalAccountInstrument
      type: object
      properties:
        instrument_type:
          type: string
          description: Type of this instrument
          enum:
            - STORED_PAYPAL_ACCOUNT
      required:
        - instrument_type
      x-internal: false
    GiftCertificate:
      title: GiftCertificate
      type: object
      properties:
        type:
          type: string
          example: gift_certificate
        gift_certificate_code:
          type: string
          example: ABC-DEF-GXX
      x-examples:
        example-1:
          type: gift_certificate
          gift_certificate_code: ABC-DEF-GXX
    StoreCredit:
      title: StoreCredit
      type: object
      properties:
        type:
          type: string
          example: store_credit
      x-examples:
        example-1:
          type: store_credit
