openapi: 3.0.0
info:
  title: Order
  version: v3
  description: Order information manage.
servers:
  - url: 'https://api-b2b.bigcommerce.com/api/v3/io'
tags:
  - name: Order
    description: Customer's Orders management.
paths:
  /orders:
    get:
      summary: Get Orders
      tags:
        - Order
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                allOf:
                  - properties:
                      code:
                        type: integer
                        x-stoplight:
                          id: 76gyd4yyjty80
                      meta:
                        type: object
                        x-stoplight:
                          id: 1evuk40zom0ql
                        properties:
                          message:
                            type: string
                            x-stoplight:
                              id: 5yv54gqn8i67q
                          pagination:
                            type: object
                            x-stoplight:
                              id: p9f5we603fqdp
                            properties:
                              totalCount:
                                type: integer
                                x-stoplight:
                                  id: yw154d60m18xq
                              limit:
                                type: integer
                                x-stoplight:
                                  id: rpbs8dbhk2jjv
                              offset:
                                type: integer
                                x-stoplight:
                                  id: tfteb0pm5evsp
                      data:
                        type: array
                        items:
                          allOf:
                            - $ref: https://raw.githubusercontent.com/bigcommerce/docs/main/docs/b2b-edition/models/order/order.yaml
                            - $ref: https://raw.githubusercontent.com/bigcommerce/docs/main/docs/b2b-edition/models/extra_fields/extra_field_values.yaml
                type: object
              examples:
                without-extra-fields:
                  value:
                    code: 200
                    meta:
                      message: SUCCESS
                    data:
                      - id: 1
                        createdAt: 1574999690
                        updatedAt: 1574999690
                        bcOrderId: 11
                        totalIncTax: 10.5
                        poNumber: bj256
                        cartId: 1
                        companyId: 12
                        usdIncTax: 11
                        currencyCode: USD
                        items: 4
                        status: completed
                        customStatus: my-completed
                        money: '{"currency_location": "left", "currency_token": "$", "decimal_token": ".", "decimal_places": 2, "thousands_token": ","}'
                        channelId: 1
                        channelName: string
                with-extra-fields:
                  value:
                    code: 200
                    meta:
                      message: SUCCESS
                    data:
                      - id: 1
                        createdAt: 1574999690
                        updatedAt: 1574999690
                        bcOrderId: 11
                        totalIncTax: 10.5
                        poNumber: bj256
                        cartId: 1
                        companyId: 12
                        usdIncTax: 11
                        currencyCode: USD
                        items: 4
                        status: completed
                        customStatus: my-completed
                        money: '{"currency_location": "left", "currency_token": "$", "decimal_token": ".", "decimal_places": 2, "thousands_token": ","}'
                        channelId: 1
                        channelName: string
                        extraFields: [{
                          "fieldName": "test field",
                          "fieldValue": "test"
                        }]
      operationId: get-orders
      security:
        - authToken: []
      description: Get all orders
      parameters:
        - schema:
            type: integer
          in: query
          name: companyId
          description: Company ID field
        - $ref: '#/components/parameters/limit'
        - $ref: '#/components/parameters/offset'
        - $ref: '#/components/parameters/orderBy'
        - $ref: '#/components/parameters/sortBy'
        - name: minModified
          in: query
          description: Minimum modified timestamp
          allowEmptyValue: true
          schema:
            type: number
            format: time
        - name: maxModified
          in: query
          description: Maximum modified timestamp
          allowEmptyValue: true
          schema:
            type: number
        - name: minCreated
          in: query
          description: Minimum created timestamp
          allowEmptyValue: true
          schema:
            type: number
        - name: maxCreated
          in: query
          description: Maximum created timestamp
          allowEmptyValue: true
          schema:
            type: number
        - schema:
            type: boolean
            default: false
            example: false
          in: query
          name: showExtra
          description: Show extra field in response
        - schema:
            type: integer
            example: 1
          in: query
          name: bcOrderId
          description: Unique order ID in BigCommerce store
        - schema:
            type: array
          in: query
          name: channelIds
          description: BigCommerce channel ids
    post:
      tags:
        - Order
      summary: Create an Order
      operationId: post-orders
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                allOf:
                  - $ref: https://raw.githubusercontent.com/bigcommerce/docs/main/docs/b2b-edition/models/utils/response-object.yaml
                  - type: object
                    properties:
                      data:
                        allOf:
                          - $ref: https://raw.githubusercontent.com/bigcommerce/docs/main/docs/b2b-edition/models/order/order.yaml
                description: Successful created
              examples:
                example-1:
                  value:
                    code: 200
                    meta:
                      message: SUCCESS
                    data:
                      createdAt: 1574999690
                      updatedAt: 1574999690
                      bcOrderId: 11
                      totalIncTax: 10.5
                      poNumber: bj256
                      cartId: 1
                      companyId: 12
                      usdIncTax: 11
                      currencyCode: USD
                      items: 4
                      status: completed
                      customStatus: my-completed
                      money: '{"currency_location": "left", "currency_token": "$", "decimal_token": ".", "decimal_places": 2, "thousands_token": ","}'
                      id: 1
                      channelName: msf1
        '400':
          $ref: '#/components/responses/400'
      description: Create an order
      requestBody:
        content:
          application/json:
            schema:
              allOf:
                - type: object
                  properties:
                    bcOrderId:
                      type: integer
                      description: Order ID in bigcommerce
                    customerId:
                      type: integer
                      description: Customer ID of order creater
                    poNumber:
                      type: string
                      description: PO payment method message.
                  required:
                    - bcOrderId
                    - customerId
                - $ref: https://raw.githubusercontent.com/bigcommerce/docs/main/docs/b2b-edition/models/extra_fields/extra_field_values.yaml
            examples:
              example-1:
                value:
                  bcOrderId: 0
                  customerId: 0
                  poNumber: bc156
                  extraFields: [{
                    "fieldName": "test field",
                    "fieldValue": "test"
                  }]
  '/orders/{bcOrderId}':
    parameters:
      - $ref: '#/components/parameters/bcOrderId'
    get:
      summary: Get an Order
      tags:
        - Order
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                allOf:
                  - $ref: https://raw.githubusercontent.com/bigcommerce/docs/main/docs/b2b-edition/models/utils/response-object.yaml
                  - type: object
                    properties:
                      data:
                        allOf:
                          - $ref: https://raw.githubusercontent.com/bigcommerce/docs/main/docs/b2b-edition/models/order/order.yaml
                          - $ref: https://raw.githubusercontent.com/bigcommerce/docs/main/docs/b2b-edition/models/extra_fields/extra_field_values.yaml
              examples:
                example-1:
                  value:
                    code: 200
                    meta:
                      message: SUCCESS
                    data:
                      createdAt: 1574999690
                      updatedAt: 1574999690
                      bcOrderId: 11
                      totalIncTax: 10.5
                      poNumber: bj256
                      cartId: 1
                      companyId: 12
                      usdIncTax: 11
                      currencyCode: USD
                      items: 4
                      status: completed
                      customStatus: my-completed
                      money: '{"currency_location": "left", "currency_token": "$", "decimal_token": ".", "decimal_places": 2, "thousands_token": ","}'
                      id: 1
                      extraFields: [{
                          "fieldName": "test field",
                          "fieldValue": "test"
                        }]
                      channelId: 1
                      channelName: string
        '404':
          $ref: '#/components/responses/404'
      operationId: get-orders-orderId
      description: Get an order detail info
      security:
        - authToken: []
    put:
      tags:
        - Order
      summary: Update an Order
      operationId: put-orders-orderId
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                allOf:
                  - $ref: https://raw.githubusercontent.com/bigcommerce/docs/main/docs/b2b-edition/models/utils/response-object.yaml
                  - type: object
                    properties:
                      data:
                        allOf:
                          - $ref: https://raw.githubusercontent.com/bigcommerce/docs/main/docs/b2b-edition/models/order/order.yaml
              examples:
                example-1:
                  value:
                    code: 200
                    meta:
                      message: SUCCESS
                    data:
                      createdAt: 1574999690
                      updatedAt: 1574999690
                      bcOrderId: 11
                      totalIncTax: 10.5
                      poNumber: bj256
                      cartId: 1
                      companyId: 12
                      usdIncTax: 11
                      currencyCode: USD
                      items: 4
                      status: completed
                      customStatus: my-completed
                      money: '{"currency_location": "left", "currency_token": "$", "decimal_token": ".", "decimal_places": 2, "thousands_token": ","}'
                      id: 1
                      extraFields: [{
                        "fieldName": "test field",
                        "fieldValue": "test"
                      }]
        '404':
          $ref: '#/components/responses/404'
      description: Update order's poNumnber and extraFields. you shoud send least one field.
      requestBody:
        content:
          application/json:
            schema:
              allOf:
                - type: object
                  properties:
                    poNumber:
                      type: string
                      example: bj256
                      description: PO number
                    status:
                      type: string
                      description: Status of this order
                      example: Awaiting Payment
                    statusCode:
                      type: integer
                      description: Status code of this order
                      example: 1
                    syncChannel:
                      type: boolean
                      x-stoplight:
                        id: 5l2853rc7hqzc
                      description: Sync channel info from BC. Only can be used when MSF is enabled.
                - $ref: https://raw.githubusercontent.com/bigcommerce/docs/main/docs/b2b-edition/models/extra_fields/extra_field_values.yaml
            examples:
              example-1:
                value:
                  poNumber: bj256
                  extraFields: [{
                    "fieldName": "test",
                    "fieldValue": "test"
                  }]
  '/customers/{customerId}/orders/company':
    put:
      tags:
        - Order
      summary: Update Orders' company attribute
      operationId: put-orders-company
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                allOf:
                  - $ref: https://raw.githubusercontent.com/bigcommerce/docs/main/docs/b2b-edition/models/utils/response-object.yaml
                  - type: object
                    properties:
                      data:
                        type: object
                        properties:
                          total:
                            type: integer
                            description: Converted orders amount.
              examples:
                example-1:
                  value:
                    code: 200
                    meta:
                      message: SUCCESS
                    data:
                      total: 10
        '404':
          $ref: '#/components/responses/404'
      description: |-
        Update the orders belong to a B3 company to another B3 company.
        Convert orders from user's former BC group into user's present BC group.
      security:
        - authToken: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                bcGroupId:
                  type: integer
                  description: User's former group ID in bigcommerce.
              required:
                - bcGroupId
        description: ''
    parameters:
      - schema:
          type: integer
        name: customerId
        in: path
        required: true
        description: BigCommerce customer id.
  '/orders/{bcOrderId}/products':
    parameters:
      - $ref: '#/components/parameters/bcOrderId'
    get:
      summary: Get Order's Products
      tags:
        - Order
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                allOf:
                  - $ref: https://raw.githubusercontent.com/bigcommerce/docs/main/docs/b2b-edition/models/utils/response-object.yaml
                  - type: object
                    properties:
                      data:
                        type: array
                        items:
                          allOf:
                            - $ref: https://raw.githubusercontent.com/bigcommerce/docs/main/docs/b2b-edition/models/order/order-product.yaml
                            - type: object
                              properties:
                                productId:
                                  type: integer
                                  description: Product ID field in BigCommerce.
                                  example: 1
              examples:
                example-1:
                  value:
                    code: 200
                    meta:
                      message: SUCCESS
                    data:
                      - id: 1
                        createdAt: 1574999690
                        updatedAt: 1574999690
                        productName: LGM Spicy Chili Crisp
                        variantSKU: 7.41 Ounce (Pack of 12)
                        variantId: 12
                        options: '[{"id": 715, "option_id": 41, "order_product_id": 670, "product_option_id": 121, "display_name": "Gauge", "display_value": "12", "value": "123", "type": "Multiple choice", "name": "Gauge1576218034-477", "display_style": "Dropdown"}, {"id": 716, "option_id": 42, "order_product_id": 670, "product_option_id": 122, "display_name": "Leg 1 (inches)", "display_value": "5", "value": "5", "type": "Text field", "name": "Leg-1-(inches)1576218034-477", "display_style": ""}]'
                        productBrandName: LGM
                        quantity: 10
                        productId: 1
        '404':
          $ref: '#/components/responses/404'
      operationId: get-orders-orderId-products
      description: Get order's product detail.
      security:
        - authToken: []
  '/customers/{customerId}/orders/b2b':
    parameters:
      - schema:
          type: integer
        name: customerId
        in: path
        required: true
        description: BigCommerce customer id.
    put:
      tags:
        - Order
      summary: Update Customer's BC Orders
      operationId: put-customers-customerId-orders-bc
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                allOf:
                  - $ref: https://raw.githubusercontent.com/bigcommerce/docs/main/docs/b2b-edition/models/utils/response-object.yaml
                  - type: object
                    properties:
                      data:
                        type: object
                        properties:
                          total:
                            type: integer
                            description: Converted orders amount.
              examples:
                example-1:
                  value:
                    code: 200
                    meta:
                      message: SUCCESS
                    data:
                      total: 11
        '404':
          $ref: '#/components/responses/404'
      description: 'Add Company identifier for BigCommerce Customer Individual Orders, which can be used to convert BigCommerce Customer Individual Orders to Company-level Orders.'
      security:
        - authToken: []
  /orders/extra-fields:
    get:
      summary: Get order extra field configs
      tags:
        - Order
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                allOf:
                  - $ref: https://raw.githubusercontent.com/bigcommerce/docs/main/docs/b2b-edition/models/utils/response-object.yaml
                  - type: object
                    properties:
                      data:
                        type: array
                        items:
                          $ref: https://raw.githubusercontent.com/bigcommerce/docs/main/docs/b2b-edition/models/extra_fields/extra_fields.yaml
                      meta:
                        $ref: https://raw.githubusercontent.com/bigcommerce/docs/main/docs/b2b-edition/models/utils/pagination.yaml
      operationId: get-orders-extra-fields
      description: Get order extra field configs
      parameters:
        - $ref: https://raw.githubusercontent.com/bigcommerce/docs/main/docs/b2b-edition/specs/api-v3/user/user.yaml#/components/parameters/offset
        - $ref: https://raw.githubusercontent.com/bigcommerce/docs/main/docs/b2b-edition/specs/api-v3/user/user.yaml#/components/parameters/limit
components:
  schemas: {}
  parameters:
    limit:
      name: limit
      in: query
      required: false
      schema:
        type: integer
        example: 15
        default: 10
        maximum: 200
        minimum: 1
      description: Pagination limit
    offset:
      name: offset
      in: query
      schema:
        type: integer
        example: 5
        minimum: 0
      description: Pagination offset
    orderBy:
      name: orderBy
      in: query
      required: false
      schema:
        type: string
        enum:
          - DESC
          - ASC
        default: DESC
        example: ASC
      description: Order by
    orderId:
      name: orderId
      in: path
      required: true
      schema:
        type: integer
      description: Unique order ID
    bcOrderId:
      name: bcOrderId
      in: path
      required: true
      schema:
        type: integer
      description: Unique order ID in BigCommerce Store
    sortBy:
      name: sortBy
      in: query
      required: false
      schema:
        type: string
        default: updatedAt
        enum:
          - createdAt
          - updatedAt
        example: updatedAt
      description: The response sorted by which field
  responses:
    '400':
      description: Request Error
      content:
        application/json:
          schema:
            description: ''
            type: object
            properties:
              code:
                type: number
              data:
                type: array
                items:
                  required: []
                  properties: {}
              meta:
                type: object
                properties:
                  message:
                    type: string
                    minLength: 1
                required:
                  - message
            required:
              - code
              - data
              - meta
            x-examples:
              example-1:
                code: 400
                data: []
                meta:
                  message: The order already exists.
          examples:
            example-1:
              value:
                code: 400
                data: []
                meta:
                  message: The order already exists.
    '404':
      description: Resource not found error
      content:
        application/json:
          schema:
            description: ''
            type: object
            x-examples:
              example-1:
                code: 404
                data: {}
                meta:
                  message: Not Found Error
            properties:
              code:
                type: integer
                example: 404
              data:
                type: object
              meta:
                type: object
                properties:
                  message:
                    type: string
                    example: Not Found Error
                    description: Error message of this response
            required:
              - code
              - data
          examples:
            example-1:
              value:
                code: 404
                data: {}
                meta:
                  message: Not Found Error
  examples: {}
  securitySchemes:
    authToken:
      name: authToken
      type: apiKey
      in: header
security:
  - authToken: []
x-stoplight:
  docs:
    includeDownloadLink: true
    showModels: false
